### ISSUE TITLE
Opening socket connection to server localhost/127.0.0.1:2181

### ISSUE THREAD

**Issue by dawidmalina** [naver/pinpoint#1369]
Console logs on web and collector app shows such messages:
```
21:38:36 INFO (o.a.z.ClientCnxn                   :975) Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
21:38:36 WARN (o.a.z.ClientCnxn                   :1102) Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
```
Regular logs are ok and app seems to work. Should I configure sth?

**Comment by koo-taejin** [comment]
If you not get error message continuously.
you can skip it. 
because ClientCnxn try to connect  zookeeper continuously.

If not, You must check you're zookeeper is running. 
Commonly 'connection refused' error occurs when host is found, but the host's port is unavailable.

**Comment by dawidmalina** [comment]
Yes message appears continuously. Is it possible to hide this or make it optional (I mean is it possible to disable zookeeper in single node setup)?

Especially for collector which in my opinion should be independent.

**Comment by dawidmalina** [comment]
Ok I found this option `cluster.enable=true`. Closing ticket.

**Comment by riverman282915** [comment]
I have the same error. 
can you please tell me which file did you apply that option ? is it in the zookeeper.conf ?

**Comment by koo-taejin** [comment]
@riverman282915 

```
Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
```

This error is occurred by connecting failed to zookeeper which has 127.0.0.1:2181 address.
Please check zookeeper is running.

**Comment by riverman282915** [comment]
thanks, My zookeeper is running, but the bookeeper.conf needs matadatauri defined with zookeeper pods.
it turns out the error is caused by this below.
`14:13:07.675 [main] INFO org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase - Initialize zookeeper metadata driver at metadata service uri zk+null://localhost:2181/ledgers : zkServers = lo Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss calhost:2181, ledgersRootPath = /ledgers.`

I'm trying to follow up similar issue reported in https://github.com/apache/bookkeeper/issues/1756
