### ISSUE TITLE
Collector restart, application cannot show correct informations in call tree

### ISSUE THREAD

**Issue by majinkai** [naver/pinpoint#1422]
when collector restart(application keep running), call tree all display with `API-METADATA-NOT-FOUND` and server map cannot display Tomcat node.

i tried to drop and re-create hbase table, it cannot display any application in `Application Select`, then restart one of tomcat(A), it can show only one application by A. the steps are:
> 1. Application keep running
> 2. Stop collector
> 3. Drop hbase tables with `hbase-drop.hbase`
> 4. Create hbase tables with `hbase-create.hbase`
> 5. Start collector
> 6. Visit some page

**Comment by majinkai** [comment]
My English is not very good, please forgive me

**Comment by Xylus** [comment]
Not a problem at all!

The call tree displays `API-METADATA-NOT-FOUND` when the api id sent by the client cannot be found in HBase storage. This generally happens if 1) the collector was not running when the agent(client) starts, or 2) HBase was not running when the collector received these api id <-> api name mapping.

The best way to start from scratch would be to : 
1) Shut down your client(agent), collector, and hbase
2) Drop and recreate hbase tables
3) Start hbase (and wait till it's running)
4) Start collector (and wait till it's running)
5) Start client(agent)
Please note that whenever you drop and recreate hbase tables, all the data gets deleted as well.

Let me know if you've more questions.
Thanks

**Comment by majinkai** [comment]
If add/remove a plugin to collector, how to ensure that the plugin to take effect?
Must restart the application?

**Comment by Xylus** [comment]
I believe so, yes, as currently BCI's done at class-loading time.

**Comment by xulongju** [comment]
I have encountered such problems,
My steps:
1, hbase to clean up all the table data;
2, open the call stack, it will appear "API-METADATA-NOT-FOUND".
I can not reboot the pinpoint-agent at any time in the production environment.

**Comment by Thiru-Arasu** [comment]
I got same problem. 
1. Live thread is not displaying.
2. Agent status becomes as "shutdown".
3. Call stack shows "API-METADATA-NOT-FOUND".

I can't restart agent all times in the prod setup. Is there any other way to fix this problem?? 
Please help me...
