### ISSUE TITLE
what is the difference of ServiceTypeProperty[question]

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#1438]
Hi,everyone:

what is the difference?
````
    TERMINAL,
    RECORD_STATISTICS,
    INCLUDE_DESTINATION_ID
````

when i write a plugin:
1.how can I decide to use SpanRecorder or SpanEventRecorder?
2.how can I decide to use above ServiceTypeProperty when I define a ServiceType. 
3.what is difference about building application map  according above ServiceTypeProperty
4.what is relationship about these methods:recordRemoteAddress,recordEndPoint,recordDestinationId.

I write a plugin,but when render the application map, it reports error like this:
````
java.lang.NullPointerException: responseHistogramList must not be null
	at com.navercorp.pinpoint.web.applicationmap.histogram.NodeHistogram.<init>(NodeHistogram.java:80)
	at com.navercorp.pinpoint.web.applicationmap.ApplicationMapBuilder$2.createNodeHistogram(ApplicationMapBuilder.java:117)
	at com.navercorp.pinpoint.web.applicationmap.ApplicationMapBuilder.appendNodeResponseTime(ApplicationMapBuilder.java:292)
	at com.navercorp.pinpoint.web.applicationmap.ApplicationMapBuilder.build(ApplicationMapBuilder.java:91)
	at com.navercorp.pinpoint.web.applicationmap.ApplicationMapBuilder.build(ApplicationMapBuilder.java:121)
	at com.navercorp.pinpoint.web.service.FilteredMapServiceImpl.createMap(FilteredMapServiceImpl.java:288)
	at com.navercorp.pinpoint.web.service.FilteredMapServiceImpl.selectApplicationMap(FilteredMapServiceImpl.java:203)
	at com.navercorp.pinpoint.web.service.FilteredMapServiceImpl.selectApplicationMap(FilteredMapServiceImpl.java:183)
	at com.navercorp.pinpoint.web.controller.BusinessTransactionController.transactionInfo(BusinessTransactionController.java:114)
`````
what is the possible reason?

any information is welcome~

**Comment by Xylus** [comment]
Hi aximo,

**what is the difference?**
These properties are used as flags that are needed when drawing the server map. I'll give more details below (question 3).

**1. how can I decide to use SpanRecorder or SpanEventRecorder?**
Use `SpanRecorder` when starting a *Span*, `SpanEventRecorder` when starting a *SpanEvent*. For example, if you're writing a plugin that accepts a RPC call (such as Tomcat), you'll want to first create a *Span* using `SpanRecorder` (see [StandardHostValveInvokeInterceptor](/blob/master/plugins/tomcat/src/main/java/com/navercorp/pinpoint/plugin/tomcat/interceptor/StandardHostValveInvokeInterceptor.java)#createTrace), For everything else, you'll probably want to use the `SpanEventRecorder`.

**2. how can I decide to use above ServiceTypeProperty when I define a ServiceType?**
That depends on what the `ServiceType` represents. The answer to the next question below will give you a better idea.

**3. what is difference about building application map according above ServiceTypeProperty**
* `TERMINAL` - `ServiceType` with this type means that the target of this RPC won't have any further trace nodes. For example, if you're writing a MySQL plugin, you'll only be tracing the client code but not the MySQL node itself. This will normally draw the server map as : `USER -> WAS(MySQL client)`. By specifying `TERMINAL`, the server map will emulate the MySQL server node and draw the server map as : `USER -> WAS(MySQL client) -> MySQL Server`.
* `RECORD_STATISTICS` - This property indicates that whatever *Span*/*SpanEvent* the `ServiceType` represents has RPC statistics. It's almost always used for all *Spans*, and for *SpanEvents* that starts a RPC. This RPC statistics is used when drawing the server map (for edges, and for response/load charts)
* `INCLUDE_DESTINATION_ID` - Used to show the destination id in the server map, and in the call stack. Destination id is the logical name for a RPC destination (instead of your typical host:port). For example, the MySQL plugin might want to show the database name instead of the jdbc url, so it'll have this attribute and have the database name set as the `destinationId`.

**4.what is relationship about these methods : recordRemoteAddress, recordEndPoint, recordDestinationId**
**recordRemoteAddress** - Used by `SpanRecorder` (RPC receiver). Records the client host:port that sent the request.
**recordEndPoint** - Usually used by `SpanRecorder` (RPC receiver). Records the server host:port that received the request. (`SpanEventRecorder` for `TERMINAL` `ServiceType` also records this as they must emulate the receiver).
**recordDestinationId** - Used by `SpanEventRecorder` for RPC clients. Records where the RPC call is made to.

**java.lang.NullPointerException: responseHistogramList must not be null**
This is probably because the node being rendered does not have statistics. From your stack trace, it looks like the server map is rendering a WAS node. Please check if the `ServiceType` for this node has the `RECORD_STATISTICS` property.

Please let me know if you've more questions.

**Comment by aximo** [comment]
Very clear answer,thanks
