### ISSUE TITLE
Simple Java Application - No Stats

### ISSUE THREAD

**Issue by shakatechdayne** [naver/pinpoint#145]
Hi,

I have a simple java application I wanted to monitor with pinpoint. I have successfully loaded the agent and configured it in my application startup command. I have defined the application name and the agent id. In the catalina logs of the collector I can see a lot of activity including JDBC/SQL MetaData, I also so JVMGC information all being passed by the application to the collector. When I connect to the web interface I can select my application, however it does not display any data. The following is logged in the web catalina log when I select a legitimate time range and the application:

01-28 13:22:21 [DEBUG](c.n.p.r.c.PacketDecoder            :110) received ping. sending pong. [id: 0xb56e13ee, /10.32.3.143:20864 => /10.32.3.135:9994]
01-28 13:22:21 [DEBUG](c.n.p.r.c.PacketDecoder            :50) pong write success. channel:[id: 0xb56e13ee, /10.32.3.143:20864 => /10.32.3.135:9994]
13:22:24 DEBUG(c.n.p.w.c.MapController            :79 ) range:5
13:22:24 DEBUG(c.n.p.w.s.MapServiceImpl           :77 ) SelectApplicationMap
13:22:24 DEBUG(c.n.p.w.s.LinkVisitChecker         :45 ) LinkData exists. Skip finding caller. BINGODABUAT(STAND_ALONE:1000) 
13:22:24 DEBUG(p.w.d.h.HbaseMapStatisticsCallerDao:113) scan Time:Range{from=2015-01-28 13:16:59 999, to=2015-01-28 13:22:00 000, range s=300}
13:22:24 DEBUG(p.w.d.h.HbaseMapStatisticsCallerDao:67 ) There's no caller data. BINGODABUAT(STAND_ALONE:1000), Range{from=1422451044000, to=1422451344000, range=300000}
13:22:24 DEBUG(c.n.p.w.s.LinkDataSelector         :92 ) Found Caller. count=0, caller=BINGODABUAT(STAND_ALONE:1000)
13:22:24 DEBUG(c.n.p.w.s.LinkDataSelector         :352) Result of finding caller LinkDataDuplexMap{sourceLinkDataMap=LinkDataMap [{}], targetLinkDataMap=LinkDataMap [{}]}
13:22:24 DEBUG(c.n.p.w.s.LinkVisitChecker         :60 ) LinkData exists. Skip finding callee. BINGODABUAT(STAND_ALONE:1000) 
13:22:24 DEBUG(p.w.d.h.HbaseMapStatisticsCalleeDao:122) scan time:Range{from=2015-01-28 13:16:59 999, to=2015-01-28 13:22:00 000, range s=300} 
13:22:24 DEBUG(p.w.d.h.HbaseMapStatisticsCalleeDao:73 ) There's no caller data. BINGODABUAT(STAND_ALONE:1000), Range{from=1422451044000, to=1422451344000, range=300000}
13:22:24 DEBUG(c.n.p.w.s.LinkDataSelector         :145) Found Callee. count=0, callee=BINGODABUAT(STAND_ALONE:1000)
13:22:24 DEBUG(c.n.p.w.s.LinkDataSelector         :355) Result of finding callee LinkDataDuplexMap{sourceLinkDataMap=LinkDataMap [{}], targetLinkDataMap=LinkDataMap [{}]}
13:22:24 DEBUG(c.n.p.w.s.LinkDataSelector         :273) this.emulationLinkMarker:[]
13:22:24 DEBUG(c.n.p.w.a.ApplicationMapBuilder    :106) node size:0
13:22:24 DEBUG(c.n.p.w.a.ApplicationMapBuilder    :108) node size:0
13:22:24 DEBUG(c.n.p.w.a.ApplicationMapBuilder    :110) allNode:[]
13:22:24 DEBUG(c.n.p.w.a.ApplicationMapBuilder    :157) link size:0
13:22:24 DEBUG(c.n.p.w.a.ApplicationMapBuilder    :159) link size:0
13:22:24 INFO (c.n.p.w.s.MapServiceImpl           :88 ) Fetch applicationmap elapsed. 7ms

What am I missing? Why is it not returning any data? I have the agent config set to the defaults except for the collector IP set to the IP of the collector machine. Any help would be greatly appreciated.

Many thanks,

Dayne

**Comment by Xylus** [comment]
Hi Dayne,

It seems like the agent and the collector are set up okay, but the web isn't able to query any trace data.

Off the top of my head this could be due to 2 things:
First, it could be due to Hbase standalone. I've had my HBase instance kill itself occasionally while testing out the quickstart sample on my laptop. However, this would have left some errors in your collector's catalina log. If there's nothing wrong with your collector's catalina log, it could be due to the next reason.

Application type mismatch between the agent and its trace data, which is something we're currently working on and a fix should be available soon.
But for a temporary work-around: if you are running an embedded tomcat within your java application, could you try uncommenting `profiler.applicationservertype=TOMCAT` in pinpoint.config? The file should be in your `pinpoint-agent` directory.

If the above doesn't help, please tell us a bit about the application you are running, such as if it's running an embedded container (or a custom servlet container), if it's running on Spring-Boot etc?

Thank you.
