### ISSUE TITLE
How to trace all the call stack in application?

### ISSUE THREAD

**Issue by peterxuxin** [naver/pinpoint#1567]
**EntryMethod** ---call--> **Method 1** ---call--> **Method 2** ---call--> **Method 3** ---call--> **Method 4**
How to get the call tree like exception call stack as follow:
**EntryMethod**
........|
........|---- **Mehtod 1**
................|
................|---- **Method 2** 
........................|
........................|---- **Method 3** 
................................|
................................|---- **Method 4** 
Now I just get some call info form external jars， none is my self-defined method.

**Comment by Xylus** [comment]
Hi peterxuxin,
To get custom methods traced, you need to specify them in *pinpoint.config*.

There are 2 options related to this:
* `profiler.include` - You can specify classes, or packages here. Every method in the specified classes (or packages) are traced. Does not work if the method is an **EntryMethod**.
* `profiler.entrypoint` - You can specify methods here. Works for both **EntryMethod**s and normal **Method**s. However, you can only specify 1 method from a single class currently (this is fixed in 1.5.2)

Let me know if you've more question.
Thanks

**Comment by peterxuxin** [comment]
I got it. Thanks
Is there a maximum limit of profiler.include and  profiler.entrypoint  ?
And, when 1.5.2 will be released?

**Comment by Xylus** [comment]
I don't think there is a maximum limit currently.
1.5.2 will probably be release in the next few weeks, but in the mean time you could try out 1.5.2-SNAPSHOT (if you can build from source).

**Comment by peterxuxin** [comment]
No maximum limit is a good news, my application have lots of classes.
My proxy has some problems, I will try to build it again.

**Comment by wangshihui** [comment]
hi @Xylus 
what is  " `the method is an EntryMethod`" mean?

**Comment by Xylus** [comment]
Hi @wangshihui 
"EntryMethod" is the method that starts off the span for a node. For example, a method that accepts a request in a servlet container would be an entry method.

**Comment by wangshihui** [comment]
I got that,thanks # @Xylus
