### ISSUE TITLE
current master.zip of src has issue with quickstart running of collector and web apps 

### ISSUE THREAD

**Issue by mqsquidy** [naver/pinpoint#1687]
ClassNotFoundException

04-14 16:17:40 [WARN ](o.s.w.c.s.XmlWebApplicationContext :487) Exception encountered during
context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbas
eMapStatisticsCalleeDao': Injection of autowired dependencies failed; nested exception is....

followed quickstart instructions and both collector and web had similar if not exact same exceptions and would not start.

**Comment by mqsquidy** [comment]
reverted to 1.5.2 release and all is good, sorry if issue is a duplicate, did not check first

**Comment by Xylus** [comment]
Hi mqsquidy,
Just tested 1.6.0-SNAPSHOT (master) and it seems to be working okay.
It might have been due to some code changes that didn't get included at the time you downloaded *master.zip*.

Could you try running it again with the latest code base?
Please let us know if you can't get it working.

Thanks!

**Comment by mqsquidy** [comment]
I pulled master.zip this morning and everything worked as expected.

Closing issue.
