### ISSUE TITLE
Anyway to encrypt or hidden some param「eg: password」,when view the calltree by pinpoint?

### ISSUE THREAD

**Issue by FishGel** [naver/pinpoint#1730]
Anyway to encrypt or hidden some param「eg: password」,when view the calltree by pinpoint?
We don't want these params exposed.

![image](https://cloud.githubusercontent.com/assets/7518880/14876593/d41c3844-0d48-11e6-9405-55565cc0064b.png)

**Comment by nstopkimsk** [comment]
@FishGel  You can set the properties in pinpint.conf file of agent . Pinpoint will not gather the http request parameters and sql bind variables.

1)  Not for gathering http request parameters
> profiler.tomcat.tracerequestparam=false

2) Not for gathering SQL Bind value
> profiler.jdbc.tracesqlbindvalue=false

you can set the property for each database. If the below properties are commented, the default value is  the value of profiler.jdbc.tracesqlbindvalue. 
> profiler.jdbc.mysql.tracesqlbindvalue=false
profiler.jdbc.jtds.tracesqlbindvalue=false
profiler.jdbc.oracle.tracesqlbindvalue=false 
profiler.jdbc.cubrid.tracesqlbindvalue=false

**Comment by FishGel** [comment]
@nstopkimsk  I want to assign some urls to disable http request parameter tracing not all urls.
> eg: profiler.tomcat.excludetracerequestparamurls=/login,/updatepasswrod

**Comment by pparth** [comment]
@FishGel  Generally, this is not the way to go with sensitive information. There are numerous systems that can be used for logging, tracing, profiling etc. You cannot expect from each one of them to support an elaborate way of protecting this data for you and they never really do it. The only reliable way to follow is this: if you do not want sensitive information to pass through the wire, to be written into files, to be stored in data stores etc., you need to protect them (encrypt or otherwise), all the way long. In your specific case, it is easy for anyone to sniff the url. This is not a problem for Pinpoint.

**Comment by FishGel** [comment]
@pparth  thanks

**Comment by yjqg6666** [comment]
To anyone who's interested in this topic. You could just implement [the MetaDataFilter interface](https://github.com/pinpoint-apm/pinpoint/blob/master/web/src/main/java/com/navercorp/pinpoint/web/security/MetaDataFilter.java) by yourself in the web maven module.
![image](https://user-images.githubusercontent.com/1879641/107195017-c4a1ad00-6a2b-11eb-92e0-95bf8ff34b75.png)
