### ISSUE TITLE
Corrupted(invalid depth),Corrupted(invalid sequence)

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#1812]
I have some trouble .
Why do I usually find this Error from my pinpoint call tree ?
How did it occur ? 
Where are the errors ? Is it at pinpoint-Web , pinpoint-Agent or pinpoint-Collector ?
How can I avoid that ?

Thanks for your team

**Comment by Xylus** [comment]
Hi Eilikce, sorry for the late reply.
Corrupted data in the call tree are usually due to span/span events being dropped on the way to the collector.

It's quite tricky to detect if this is exactly the case here, but you could try [increasing the read socket buffer size](https://github.com/naver/pinpoint/blob/master/collector/src/main/resources/pinpoint-collector.properties#L40) to something like 4194304.
You can do this by running the command below in Linux.
```
sudo sysctl -w net.core.rmem_max=4194304
```
