### ISSUE TITLE
About max length of app name and agent id

### ISSUE THREAD

**Issue by lucasxu00** [naver/pinpoint#1884]
We noticed the length defined in PinpointConstants is APPLICATION_NAME_MAX_LEN = 24, AGENT_NAME_MAX_LEN = 24.Why this length is limited as 24? And could we change it longer such as 100, will it have effect on performance of hbase or pinpoint-web?
Thank you so much.

**Comment by Xylus** [comment]
Hi lucasxu00,
The length limits were mainly due to them being used as part of hbase row keys and 24 seemed like a good number for it. Agent id in particular is used in almost all of the rowkeys, and every single key/value will be storing this so keep this in mind when raising this.

We hope to change all this by going with a number based id system mapped to actual application names and agent ids (but not any time soon).

**Comment by lucasxu00** [comment]
@Xylus Thank you for the reply.
