### ISSUE TITLE
docker images not available

### ISSUE THREAD

**Issue by olafgeibig** [naver/pinpoint#2031]
I tried to run the docker-compose script: 

> Error: image naver/pinpoint-hbase not found

**Comment by dawidmalina** [comment]
@olafgeibig docker-compose.yml file points to images which are created during `mvn docker:build` phase.

If you just want to give a try pinpoint you may check my docker images: https://hub.docker.com/r/dawidmalina and docker-compose.yml from https://github.com/dawidmalina/docker-pinpoint

But if you want to try development branch you should build pinpoint by yourself and then build local images.

**Comment by olafgeibig** [comment]
Thanks Dawid Malina's yml is working for me, except that I can't create accounts and alerts. Probably because MySQL is missing from his docker-compose?

**Comment by Xylus** [comment]
@olafgeibig 
Hi Olaf, alerts are not fully implemented, we just have the interface exposed as it ties in with the user system and everyone's user system is different. (We do have a plan to add LDAP support in I think)

There's a [guide](https://github.com/naver/pinpoint/blob/master/doc/alarm.md#2-implementation--configuration) on how to implement alarm so that it works with your own user system.

**Comment by Xylus** [comment]
Please reopen the issue if you have more questions.
