### ISSUE TITLE
Callstack missing if application started before monitor app

### ISSUE THREAD

**Issue by msche** [naver/pinpoint#2099]
We are currently using PinPoint in a dockerized environment in which APM (PinPoint), application and db are started all in the same time. In cases the app is started before the APM the callstack is showing 'trace data' and instead of showing the method names it is showing 'API-METADATA-NOT-FOUND'. The inspector data is also missing. There is however data shown in the server map.

**Comment by Xylus** [comment]
@msche `*-METADATA-NOT-FOUND` is shown when the corresponding metadata for API, SQL, or String is not found.
The agent does not send method/class names (API), SQLs, and some String constants every time a trace generates them.
Instead, we assign an integer id on them the first time they are generated and send this mapping info (metadata) to the collector.
This way, we only need to send the id afterwards instead of the whole byte array which saves a ton of network bandwidth + storage space.

The drawback is if these mappings are lost there is no way to recover them, which looks to be the case you're seeing. Make sure your collector is up and running before starting up your agents. API metadata are mostly sent on application startup so make sure the collector is running before you start your agent application.

**Comment by msche** [comment]
Hi HyunGil,

Would it be an option to repeat sending them if the response is an
exception?

Cheers,
Mark
Op 21 sep. 2016 03:53 schreef "HyunGil Jeong" <notifications@github.com>:

**Comment by Xylus** [comment]
@msche Yes definitely! In fact that's exactly our plan for how we're looking to fix it.

**Comment by Xylus** [comment]
Please reopen the issue if you have more questions.

**Comment by dinesh4747** [comment]
Referring to this issue - https://github.com/naver/pinpoint/issues/6496 @Xylus - can you please help me in solving this issue since I am facing same issue agent starttime of metadata was differing when collector is received due to which getting "API-METADATA-NOT-FOUND".

It would be of great help if you could help me here and just show some direction to resolve the same
