### ISSUE TITLE
Can I config my own response summary chart?~

### ISSUE THREAD

**Issue by iwin4aids** [naver/pinpoint#2140]
![image](https://cloud.githubusercontent.com/assets/16768783/19266699/5c9df5b0-8fdd-11e6-876c-cb9bb55ea2d4.png)
As you see above, the default response summary chart shows that all responses are grouped by 1S/3S/5S/slow(>5S) and error(transaction failed),can i config the 5 labels?
I find the front js code like this :
![image](https://cloud.githubusercontent.com/assets/16768783/19266860/2c1e8142-8fde-11e6-83c1-a313cee80be1.png)
But I'm not familiar with angularjs, so could you show me how the '$timeout' be configured ?

Best wishes!!!

**Comment by Xylus** [comment]
Hi iwin4aids, sorry for the late reply.
Data are preslotted into *1s/3s/5s/Slow/Error* according to the node's `ServiceType` and cannot be re-categorized when querying from web.
This was done mainly due to performance reasons and **might** be changed in the future to be configurable.

However, if you're simply trying to rename the labels, for example changing *Slow* to *>5s*, this should be possible.
