### ISSUE TITLE
can't get full call tree 

### ISSUE THREAD

**Issue by wzy25** [naver/pinpoint#2226]
I've written a test bean ,the call graph is following :
w1.jsp->wzy.TestWrapper:test-> wzy.jdbc.TestBean:testJdbc (jdbc call)
                                                 ->wzy.TestSleep:test: (jdbc call)
                                                -> sleep
                                                  ->sleep

The call graph get from appdynamics is complete,but the call graph from pinpoint is incomplete 
call graph of pinpoint : 
 Tomcat Servlet Process
   REMOTE_ADDRESS
  	 invoke(Request request, Response response)
        connect(String string, Properties properties)
    	 	executeQuery(String string)
		connect(String string, Properties properties)
  			executeQuery(String string)
  

call graph of appdynamics : 

JSPBaseervlet:service: Unknown (execution time: 20 ms of 10299 ms total, wait time: 0 ms of 9984 ms total)
  Servlet - w1.jsp:_jspService: 115(execution time: 0 ms of 10279 ms total, wait time: 0 ms of 9984 ms total)
    java.lang.Thread:sleep: Unknown (execution time: 4998 ms of 4998 ms total, wait time: 4998 ms of 4998 ms total)
    wzy.TestWrapper:test: 11(execution time: 0 ms of 5281 ms total, wait time: 0 ms of 4986 ms total)
      wzy.jdbc.TestBean:testJdbc: 9(execution time: 184 ms of 1180 ms total, wait time: 0 ms of 996 ms total)
        JDBC (150ms):  [0]
        java.lang.Thread:sleep: Unknown (execution time: 996 ms of 996 ms total, wait time: 996 ms of 996 ms total)
      wzy.TestSleep:test: 11(execution time: 111 ms of 2105 ms total, wait time: 0 ms of 1994 ms total)
        JDBC (88ms):  [1]
        wzy.TestSleep:test2: 43(execution time: 0 ms of 997 ms total, wait time: 0 ms of 997 ms total)
          java.lang.Thread:sleep: Unknown (execution time: 997 ms of 997 ms total, wait time: 997 ms of 997 ms total)
        java.lang.Thread:sleep: Unknown (execution time: 997 ms of 997 ms total, wait time: 997 ms of 997 ms total)
      wzy.TestWrapper:test2: 33(execution time: 0 ms of 1005 ms total, wait time: 0 ms of 1005 ms total)
        java.lang.Thread:sleep: Unknown (execution time: 1005 ms of 1005 ms total, wait time: 1005 ms of 1005 ms total)
      java.lang.Thread:sleep: Unknown (execution time: 991 ms of 991 ms total, wait time: 991 ms of 991 ms total)

**Comment by Xylus** [comment]
Hi @wzy25 
The reason the call graphs are different is because the scope of what Pinpoint traces is different from AppDynamics. Pinpoint selectively defines which methods to trace as tracing, and this will be different from what AppDynamics chooses to trace (such as the `Thread.sleep()` method).
Tracing more will add more details but it will also add a lot of clutter in the call stack (and overhead), and it's the balancing act between these that leads to design decisions such as why we don't trace methods like `Thread.sleep()`.

That said, I don't think the scope of what we trace is perfect, so we'll continue to work on areas where we could trace more (or less).
Thanks!
