### ISSUE TITLE
Can pinpoint get QPS when enable sampling?

### ISSUE THREAD

**Issue by jamee** [naver/pinpoint#2272]
We can reduce the bandwidth usage by enable samping, however we also want to know the QPS of our application, average response time and error rate. 
How about this, even though sampling is enabled, only the QPS data(strip trace data) reported, if current trace contains error report it always.

**Comment by Xylus** [comment]
@jamee Very interesting ideas here, thanks for sharing them.
You can view the qps in the inspector page (TPS chart), which displays the qps independently of the sampling rate. (The average response time and error rate 

With that out of the way, let's discuss sampling strategies.
The current sampling strategy is "head-based", meaning the root node makes the sampling decision and all the child nodes follow that decision. The advantage of this approach is that it's simple and efficient, but it comes with the limitation that sampling decisions cannot be made based on certain events that occurred down the pipeline.

In order to overcome this limitation, we could employ a "tail-based", or "event-based" (making up names here) strategies. The "tail-based" approach could leave the sampling decision to the leaf nodes (there could be multiples, whose decision should we follow?), and the event-based approach could react to an event (such as an error) and make the sampling decision accordingly.
There are however, concerns and problems we need to address before we can employ these approaches.
They require all holding traces in memory until it's span is finished, which will add a lot of overhead to the application. How would we know if a span is "finished", especially in the context of asynchronous calls? What if one leaf node decides not to sample (and throws away it's trace), but another decides to sample? How would the sampling decision made by an event generated by one leaf node share it's state with another leaf node (which might have already finished it's trace)?

The points you've brought up are excellent, and ultimately, we also believe it to be best to move away from our current sampling strategy to something more adaptive.
Would love to hear more ideas on this one.
Thanks again for sharing!
