### ISSUE TITLE
How to enable Bytecode instrumentation (Automatic/Manual) in pinpoint?

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2296]
Looks like i could see only exec(ms) column in Call stack visibility 

How to get the dynamic instrumentation enabled like invocation count, CPU%, CPU Time spent in each method 

I dont see any option of Bytcode Instrumentation feature in pinpoint dashboard 

Please do let me know If I am missing something here

**Comment by Xylus** [comment]
Hi @dinesh4747 
The bytecode instrumentation is already enabled, that's how you're seeing the callstack (including exec(ms) etc).

The reason why you're not seeing CPU%, CPU time spent on each method is because we don't collect those statistics (yet?).
Invocation count is something we're working on currently.

**Comment by dinesh4747** [comment]
Hi @Xylus 

If i understand in right way that byte code instrumentation would give only the below 

1) Call Stack 
2) Exec time (ms)

But Instrumentation would give you the following as well if I am right as below:

a) Sync/Aysnc time
b) I/O Wait 
c) N/w Wait
d) CPU Time 
c) CPU % (Method level probing)

I feel that when we do byte code level automatic profiling we should be getting the above key insights as well 

Kindly let me know If I have misinterpreted anything here

**Comment by Xylus** [comment]
I think we're getting some terminologies mixed up here.
Bytecode instrumentation is a feature that enables you to modify bytecode during runtime (class load time to be exact). Simply using bytecode instrumentation doesn't give you anything except the ability to change bytecode.
We **use** bytecode instrumentation to modify various classes/methods in order to collect data needed to generate everything you see in the call stack (including execution time etc).
However, in order to also profile everything you've mentioned (I/O Wait, CPU Time, etc), we'll need to add/implement code to collect those data. Simply enabling instrumentation doesn't give you these data automatically.

If you're suggesting that it would be better if Pinpoint also collects the metrics you've mentioned, then yeh, I agree with you to an extent :)

**Comment by dinesh4747** [comment]
Hi @Xylus 

Yes - Agreed

Even I am just looking for the same sort of data
