### ISSUE TITLE
pinpoint-web run normally but show nothing with app data

### ISSUE THREAD

**Issue by adventurer2008** [naver/pinpoint#2353]
#### Description
I reinstall pinpoint 1.6.0  and everything is ok. But pinpoint-web show nothing with app data. 
I set profiler.sampling.rate to 1 from pinpoint.config of the agent. But It still was no data .

#### Environment

* Pinpoint version:1.6.0
* CentOS6.6:
* Additional details (e.g. how your collector/web is set up):

The screenshots is as below.
![1](https://cloud.githubusercontent.com/assets/15321530/21214130/c45e343e-c2d3-11e6-93b1-7a899edafa21.jpg)
![2](https://cloud.githubusercontent.com/assets/15321530/21214137/cc3270bc-c2d3-11e6-9f97-1412c479d2bc.jpg)

#### Additional Info

Pinpoint.config of agent is as below.
[pinpoint.config.txt](https://github.com/naver/pinpoint/files/653932/pinpoint.config.txt)

**Comment by Xylus** [comment]
Hi @adventurer2008 
What kind of application are you trying to trace?

**Comment by adventurer2008** [comment]
Application is Jboss4.03
It's normal when I run pinpoint 1.5.2.

**Comment by adventurer2008** [comment]
Sometimes it shows a little data as below. I feel the sample rate of pinpoint is low very much.
![3](https://cloud.githubusercontent.com/assets/15321530/21214485/ee3c6ce2-c2d5-11e6-8c53-2aa675e3fab5.jpg)

**Comment by Xylus** [comment]
I'm not too sure about the internals of jboss 4.0.3, so I can't tell you exactly what's wrong. (If you could send us your pinpoint agent log would be great)
The JBoss plugin we got was tested against *Jboss EAP version - 6.4.x*, so I'm not entirely sure if it's a version issue. (Details on how to configure for Jboss is [here](https://github.com/naver/pinpoint/blob/master/plugins/jboss/README.md))
@suraj-raturi Hi Suraj, any input on this would be greatly appreciated.

That said, if the same application worked fine on Pinpoint 1.5.2, it could very well be that jboss 4.0.3 works exactly like tomcat internally. (Since we didn't have JBoss support at all in 1.5.2)
If this is the case, you could try setting changing the following configurations in *pinpoint.config*:
```
profiler.applicationservertype=JBOSS
profiler.tomcat.conditional.transform=false
profiler.jboss.conditional.transform=true
```
OR
```
profiler.applicationservertype=JBOSS
profiler.tomcat.conditional.transform=true
profiler.jboss.conditional.transform=false
```

**Comment by adventurer2008** [comment]
Thank you very much.
Following your configuration, right now it's ok on pinpoint 1.6.0
