### ISSUE TITLE
how to create trace on my new plugin?

### ISSUE THREAD

**Issue by yoyokeen** [naver/pinpoint#2356]
#### Description

I want create a new plugin and to monitor our background module.
Now, my question is how to create trace?

//cant draw transactions chart!
 protected Trace createTrace(Object o, Object[] objects) {
        String agent=“test”;
        long agentStartTime = System.currentTimeMillis();
        long agentTransactionCount = 10;

        String id = TransactionIdUtils.formatString(agent,agentStartTime,agentTransactionCount);

        logger.info("transactionid={}", id);

        Random ra =new Random();

        long parentSpanID = ra.nextLong();
        long spanID = ra.nextLong();
        short flags =0;
        TraceId traceId = traceContext.createTraceId(id, parentSpanID, spanID, flags);

        return traceContext.continueTraceObject(traceId);

}
#### Environment

* Pinpoint version:1.6.0
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @yoyokeen 
Unless you're trying to trace a library, I wouldn't advise you to create a plugin. It'll be take a lot of work both creating and maintaining one.
Instead, we provide a way to trace custom methods by specifying them in *pinpoint.config*.
```
###########################################################
# user defined classes                                    # 
###########################################################
# Specify classes and methods you want to profile here.

# Needs to be a comma separated list of fully qualified class names, or fully qualified package names with wild card class.
profiler.include=
# Ex: foo.bar.MyClass, foo.baz.*

# Needs to be a comma separated list of fully qualified method names. Wild card not supported.
profiler.entrypoint=
# Ex: foo.bar.MyClass.myMethod, foo.bar.MyClass.anotherMethod
```

Methods specified in `profiler.entrypoint` will create a new span if one doesn't exist in thread local, whereas the classes/methods specified in `profiler.include` requires an active span in thread local in order to trace them. Please take a look [here](https://groups.google.com/forum/#!msg/pinpoint_user/4FTXxcakkTM/fLm7wVbtAAAJ) for a more detailed explanation on how the 2 options differ and how you should choose which one to use.

**Comment by yoyokeen** [comment]
You have my gratitude .
Actually, I want to monitor a BlockingQueue, how to do it?

**Comment by yoyokeen** [comment]
You have my gratitude .
Actually, I want to monitor a java BlockingQueue, how to do it?
Anyway, I also to monitor another middleware，e.g. netcool.

**Comment by Xylus** [comment]
I see.. now that makes things a little harder :)

For Blocking Queue, it wouldn't be as simple as tracing the add/offer/put, or the remove/poll/take methods. Plus, since the operations would cross thread boundaries, there'll need to be a way to propagate trace from the producer thread to the consumer thread. We normally do this for plugins via injecting trace into an object that'll be passed over ([details](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide#24-asynchronous-task)).
So you have 2 choices, if the `BlockingQueue` you're trying to monitor is inside some publicly available library, you could go ahead and make a plugin for it using [this](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide) guide. Or if it's simply part of your own code, you could specify the method that uses the `BlockingQueue` in the configurations in the previous posts. Note that this won't trace anything that happens in the consumer thread due to reasons above.

To monitor another middleware, you'll probably have to make a plugin if Pinpoint doesn't support it yet. Please take a look at our [plugin developer guide](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide) for details on how to make plugins.

**Comment by yoyokeen** [comment]
I am very grateful.
I will following the "plugin developer guide" in details.
