### ISSUE TITLE
Failed to collect the trace of spring-boot embeded tomcat applications.

### ISSUE THREAD

**Issue by ChenXiaoTemp** [naver/pinpoint#2368]
#### Description

Now the new released 1.6.0 pinpoint can not work for the embeded tomcat(for example started with spring-boot).
In the previous version, it works.
#### Environment

* Pinpoint version: 1.6.0
* OS, WAS, affected library, etc: linux,windows
* Additional details (e.g. how your collector/web is set up):

I think following is the reason:
In the com.navercorp.pinpoint.plugin.tomcat.TomcatDetector.detect(ConditionProvider) , it add provider.checkMainClass(bootstrapMains), the default valus is 
```
org.apache.catalina.startup.Bootstrap
```
Actually, this class will changed for the embeded tomcat applications. 

But we can configure it in the configuration files, I am not sure whether it should be a bug.

**Comment by Xylus** [comment]
A conditional check was added in 1.6.0 when registering class file transformer due to Tomcat and Jboss plugins modifying the same class.
So when running an application with embedded Tomcat, you've got to set `profiler.tomcat.conditional.transform=false`.

Give it a try and let me know if it works.
Thanks

**Comment by ChenXiaoTemp** [comment]
No , it can not work. I need set the profiler.tomcat.bootstrap.main to my own main class, then it works.

**Comment by Xylus** [comment]
@ChenXiaoTemp hmm that's weird.
The change introduced in 1.6.0 is this - If `profiler.tomcat.conditional.transform` is set to *true*, Pinpoint agent transforms Tomcat related classes if the application's main class is `org.apache.catalina.startup.Bootstrap`, or one of Spring Boot's 3 different launcher. If `profiler.tomcat.conditional.transform` is set to *false*, it skips the check above and Tomcat related classes should be transformed regardless of what the application's main class is.
So setting `profiler.tomcat.conditional.transform=false` should have made embedded tomcat calls to be traced even if you don't set `profiler.tomcat.bootstrap.main` to your own class. If this doesn't work as you've mentioned, there seems to be a bug somewhere that would cause this. If this is the case, could you post your agent log so we can take a closer look at this please?

Additionally, there would also be an issue where your application would show up as *STAND_ALONE* instead of *TOMCAT* even if the everything above works. This can be solved by setting `profiler.applicationservertype=TOMCAT` in *pinpoint.config* or setting `profiler.tomcat.bootstrap.main` to your own main class just like you've mentioned.

**Comment by ChenXiaoTemp** [comment]
In my local computer profiler.applicationservertype=TOMCAT still not work, only I set profiler.tomcat.bootstrap.main to the correct value, it works.
