### ISSUE TITLE
 Corrupted(invalid sequence)

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2379]
I usually find an error node from my calltree called 'Corrupted(invalid sequence)' .
Why the error node appear ?
What can I do for this issue ? Is there any config or other way can help me ?

Thanks for your team

**Comment by haininghai** [comment]
<img width="391" alt="1" src="https://cloud.githubusercontent.com/assets/16486326/21416001/1e71dc02-c84a-11e6-8b60-585f5eb6c1d8.png">
<img width="1204" alt="2" src="https://cloud.githubusercontent.com/assets/16486326/21416043/9518d89c-c84a-11e6-90ee-75d291d39211.png">

**Comment by Xylus** [comment]
Hi @Eilikce & @haininghai 
Corrupted call stack may be due to dropped span/span chunk data that never made it into hbase. It usually happens when there's too much trace data for the collector/hbase to handle.
Your collector should be logging statistics on this (every 1 second by default) to *stat.log*.
Please take a look at this file and check for `Pinpoint-UDP-Span-Worker.rejected` logs and see if the collector rejected any spans.

Another reason for this could be that there's a hole in whatever plugin that was used to trace the request (for example, a trace block that was opened but never closed). If the corrupted call stack seems to happen only when a certain method from a certain library (plugin) is traced, then this might be the culprit.
If this seems to be the problem, please tell us what library/class/method is being invoked and post the relevant agent log so that we can take a closer look.

Thanks

**Comment by haininghai** [comment]
The bandwidth of the network is not enough, the result of packet loss.

**Comment by Eilikce** [comment]
We will have a try , thank U , Xylus

**Comment by yale2** [comment]
@Eilikce  can you tell me how to solve this problem
