### ISSUE TITLE
Can I add some user information to the http headers?

### ISSUE THREAD

**Issue by CloudInsightCT** [naver/pinpoint#2402]
Hi, I want to add an extra header in the http header to get the HTTP request, for example,
HttpGet.setHeader (PINPOINT_TX_ID, "TomcatA ^ TIME ^ 1")
HttpGet.setHeader (PINPOINT_SPAN_ID, "20")
HttpGet.setHeader (PINPOINT_PARENT_SPAN_ID, "10")
HttpGet.setHeader (PINPOINT_USER_ID, "0") // This is what I added

Will I be able to add it? If so, how can I get it? thank you very much

**Comment by Xylus** [comment]
Hi @CloudInsightCT 
Yes you can add custom headers to suit your needs, but then you'll have to change interceptors for every single http entry/exit points to make use of this new header.
May I ask what it is you're trying to do? I ask because this looks like a very specific use-case for your particular environment, and propagating user id (which is part of the business logic of your application) across network boundaries shouldn't be a part of Pinpoint's responsibility.

**Comment by CloudInsightCT** [comment]
Of course you can, we want to link with the previous paragraph, we need to add a tag in http
