### ISSUE TITLE
The version of the JDK affects the tomcat's collection

### ISSUE THREAD

**Issue by Aaron-liuzl** [naver/pinpoint#2406]
We monitor a tomcat application.
When we use JDK1.6.0 _45, can be collected data.
But when we use JDK1.6.0 _07, we won't be able to collect the data.At that time we modify parameters : profiler.tomcat.conditional.transform=false  and can be collected data.

We want to know whether pinpoint supports the version of  JDK1.6.0_07?
and What is the meaning of profiler.tomcat.conditional.transform?

**Comment by Xylus** [comment]
Hi @Aaron-liuzl 
The `profiler.tomcat.conditional.transform` was added to stop multiple class file transformers being registered to the same class (ie Tomcat and JBoss plugin both adding class file transformers to `StandardHostValve`).
The option checks for the application server type and then registers the appropriate transformers from their respective plugins.
The reason why this doesn't work for you (more specifically for jdk 1.6.0_27) is because application server type can only be detected properly from jdk 1.6.0_25 onwards.

What you can do to work around the problem is
1. do what you've done and set `profiler.tomcat.conditional.transform=false` and leave `profiler.jboss.conditional.transform=true`, or
2. upgrade your java version to 1.6.0_25 or later

Hope I've explained everything clearly, let me know if you've more questions.
Thank!

**Comment by Aaron-liuzl** [comment]
Why can the pinpoint 1.5.2  monitoring the  application of jdk1.6.0 _07?
What changed in pinpoint1.6.0?

**Comment by Xylus** [comment]
The conditional check for class file transformer registration is what's been added.
In 1.5.2, there was no JBoss plugin, so we didn't need this check, and Tomcat plugin always added it's class file transformers.
But as the JBoss plugin got merged, pinpoint agent would throw an error because both Tomcat plugin, and JBoss plugin would add their own transformers for `StandardHostValve` class.

It was either this, or manually having to force users enable/disable Tomcat/JBoss (and SpringBoot) plugin depending on the application type they were running.
