### ISSUE TITLE
The numbe in Scatter Chart is not same as Response Summary

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2423]
Why the number called success of Scatter Chart is not equals to Response Summary ? The Error num in Scatter Chart is not same as Response Summary either , why?

![pinpoint-right](https://cloud.githubusercontent.com/assets/17841648/21601199/4015b910-d1c2-11e6-9566-279f1284961b.png)

**Comment by Xylus** [comment]
Hi @Eilikce 
The numbers between the scatter chart and response summary may be different due to the reasons explained in #2381. The response summary chart numbers work the same way as the server map numbers so they may be different from the scatter chart numbers.

The "Error" number above the scatter chart is the number of agents that had an error.
So in your case, *Total 1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Error 1* means there is 1 agent registered under the application name, of which 1 agent had a failed transaction.

**Comment by Eilikce** [comment]
Why pinpoint use different time wides in these charts ? The charts usually can be see in a common web page . Is better that use same time wides ?

**Comment by Xylus** [comment]
The scatter chart data on the other hand have 1 second granularity, so these can be differentiated in 1 second interval.
The server map, response summary, and load chart data on the other hand, are stored in 1 minute granularity (the collector aggregates these in memory and flushes them every minute due to performance reasons).

So the only way to make everything use the same time intervals would be to query everything in 1 minute granularity. This means if you query for 10:15:30 ~ 10:20:30 data, the scatter chart will query everything from 10:15:00 ~ 10:21:00 and display these. This would probably make all the numbers sync up, but then you lose the ability to easily select transactions that happened before 10:20:30 (you'll have to carefully drag on the scatter chart).

So in the end, you've got to decide what's more important - make the numbers match, or provide a way to filter out the scatter chart more accurately depending on the query time.
We chose the latter.
