### ISSUE TITLE
Question: Is there a way to capture response headers and show in pinpoint.

### ISSUE THREAD

**Issue by irocks04** [naver/pinpoint#2513]
#### Description

This works fine and it shows great amount of information but do we have a capability to capture even the response headers.
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

**Comment by xinweiwei** [comment]
Hi , @irocks04 
I just wanna say that I have been trying a problem which is similar with your question for about 2 weeks. In the company I work in . we use pinpoint to get the span , and I need to use pinpoint to implement a function which is changing the content of response . so how to ,showing or not , capture response headers , I want to list several keys in this process.

first of all , what kind of server do you use , tomcat , jetty or else ? The method is defferent with the server you choose, because the implement totally depends on the classes .

if capturing the response headers is enough ,you can just weave the function which is associated with getting or setting the response headers ,and get the headers in your weaving function.

attention that , maybe its not supposed to change the filter method and add your customized filter ,because some request will new a response in server interface.

Hope this can help.
