### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/zookeeper/server/ZooTrace

### ISSUE THREAD

**Issue by feiyangzhi** [naver/pinpoint#2628]
#### Description

when i deploy pinpoint-collector to tomcat webapps. and then start tomcat, appears the error.

#### Environment

* Pinpoint version:1.6.0
* ubuntu 16  LTS

**Comment by Xylus** [comment]
Hi @feiyangzhi 
Is this occurring when Tomcat shuts down? (https://issues.apache.org/jira/browse/ZOOKEEPER-1394)
If so, it might be that your collector instance is failing to start up due to some other reason and the NoClassDefFoundError on ZooTrace is a result of that.
Could you post the collector log please?

**Comment by feiyangzhi** [comment]
you are right,  i error configure hbase address in pinpoint-collector's hbase.properties, which cause the exception. thanks !
