### ISSUE TITLE
Help Help Help ----- Which table's TTL could be modify ?

### ISSUE THREAD

**Issue by koalton** [naver/pinpoint#2653]
Help Help Help !!
Which table's TTL could be modify ?
In my PP,I just want to stored all traces 7 days ,how could i do ?
I mean which table i can modify the TTL ??
Traces and TraceV2 ,Why Traces table has no data ?

**Comment by chenguoxi1985** [comment]
Hi  koalton,

It depends on your configuration that pinpoint uses Traces or TracesV2. Please see your collecor and web configuration files:

`# span.binary format compatibility = v1 or v2 or compatibilityMode
web.span.format.compatibility.version=compatibilityMode`

`# span.binary format compatibility = v1 or v2 or dualWrite
collector.span.format.compatibility.version=v2`

This feature is at https://github.com/naver/pinpoint/issues/1819

**Comment by koalton** [comment]
# @chenguoxi1985 ，would you like tell me how could i do so that store datas for just 7 days? 
i modify all table TTL 604800 (7 days) except AgentInfo,ApiMetaData,ApplicationIndex which TTL is 31536000 (365 Days),but when i come in Call-Tree it shows me "Corrupted(invalid sequence)" # like blow 

![222](https://cloud.githubusercontent.com/assets/22216568/23498909/cbf0c1ee-ff64-11e6-94fd-eb4090db8ec8.jpg)

**Comment by koo-taejin** [comment]
Hi koalton

API-META-DATA-NOT-FOUND can be releated with TTL.
But "Corrupted (invalid sequence)" would not be the case.

There are two cases when an invalid sequence occurs.

1. If there are too many trace events for a target node, there is a limit to the number of collector and hbase protections
2. If some trace packets (UDP packets) are lost 

Perhaps in your case, seems to be a 1 situation because every request  have invalid sequence. 

I suggest you to increase the number of `collector.spanEvent.sequence.limit`(pinpoint-collector.properties)

thanks.

**Comment by chenguoxi1985** [comment]
Hi koalton,

The callstack view is highly based on Traces table. I suggest you set Traces and TracesV2 to 7 days. Then expiry callstack would not be show.

**Comment by koalton** [comment]
@chenguoxi1985 ,3Q, i will try it as your suggestion .
@koo-taejin ,U really do me a big favor,thanks a lot .i hava reduce  my record tarce nodes,then it works
