### ISSUE TITLE
all agent traffic in only TCP

### ISSUE THREAD

**Issue by teambullseye** [naver/pinpoint#2666]
a configurable option in pinpoint agent config so all traffic from agent is in only TCP., it opens up options for further enhancements., ex., more load balancer options for collector

**Comment by jiaqifeng** [comment]
Using TCP may cause more cpu/memory usage on app side. What kind of load balancer options for collector do you want? Can you give some example?

**Comment by teambullseye** [comment]
we wanted to use AWS Elastic load balancer for collectors, but it doesn't support UDP, so we had to change this to all TCP in our implementation, we did the performance testing and the impact to cpu/memory is negligible. we have the code ready and will make a pull request in a couple of days. anyways it will be a configurable option in agent config, so agents can choose to use only TCP or both UDP and TCP. you can set that option to false by default, and if anyone wants to use they can enable it to true in agent config

**Comment by jiaqifeng** [comment]
I used another could service which provides udp LB service so this does not truble me. Supporting TCP instead of UDP brings more accurate conrol for randomed span lossage in high pressure situation when using UDP. I am considering the senario for using tcp for key applications which cannot afford the message lossage and udp for other common apps.
