### ISSUE TITLE
Features request on Distributed Call Flow: Collapse and sorting

### ISSUE THREAD

**Issue by ha02148** [naver/pinpoint#292]
Hi,

Is it possible to collapse the methods by default. It is easier to view when there are hundreds or thousands of methods.  Also, the ability to sort the gap and time to see which took the longest.

Thanks

![feature_request](https://cloud.githubusercontent.com/assets/5472821/6965451/88645fa2-d91f-11e4-8092-d0618e80f6af.png)

**Comment by minwoo-jung** [comment]
답변 달고 있으신분 없으시면 제가 하겠습니다.
 
정민우 드림 
 
-----Original Message-----

**Comment by minwoo-jung** [comment]
Hi

Thank you for providing us with such a detailed description of your question.

The main purpose of distributed call flow view is to show the method call order in a tree format.
If slow section is exist, we should see with method tree, easy to find problem.
In order to analyze a problematic section, it is important to check the overall call flow. 
It would not be helpful in analyzing the problem if the call tree is sorted by a different property.

However we have a plan to show the slow sections more easily.

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [pinpoint] Features request on Distributed Call Flow: Collapse and sorting (#292)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-04-06 00:00 ~ 2015-04-10 23:59 GMT +09:00]<br>일본 출장 중입니다. 업무시간 중간 중간 대응 가능한 것은 대응하도록 하겠습니다. <br>급한 용무는 김진녕님에게 부탁드립니다.  <br>
--------------------------------------------
