### ISSUE TITLE
Pinpoint web not starting up

### ISSUE THREAD

**Issue by vivekbny** [naver/pinpoint#3189]
Hi,

I am trying to deploy pinpoint in our linux machine.

Hbase is up and running in the same machine.

I deployed collector and web war files in the webapps folder, started it. But the UI is not coming up in the webbrowser. Getting 404 error. 

Can you help please me at the ealriest.

Attaching the logs for further debugging. 
[catalinalog.txt](https://github.com/naver/pinpoint/files/1176197/catalinalog.txt)

Thanks,
vivek

**Comment by Xylus** [comment]
Hi @xbblq7n 
There seems to be a lot going on from your log. Please check out the exceptions for their causes. I'm not sure I can help you much as they seem to be related to your deployment environment.
(eg error in opening zip due to permission and too many open files due to file limit?)

One thing I would like to suggest though is to try to launch the collector and web in separate Tomcat instances and see if that works better.

**Comment by xbblq7n** [comment]
Thanks @Xylus. 

I am not able to get the JDBC details in pinpoint. Please help me on how to get them.

**Comment by xbblq7n** [comment]
Can somebody help on this?

**Comment by Xylus** [comment]
@xbblq7n You shouldn't need to do anything to trace JDBC details, they should be traced automatically given the agent started up okay.
Also note that some versions of whatever jdbc driver you're using might not be supported (ie mysql driver 6+ support is only available from the master branch).

If you had provided more details on your issue such as the jdbc driver and version you're using, it would have been much easier to help you.
Please provide more details on the issue if you're looking for a solution.

**Comment by xbblq7n** [comment]
I will give you the details shortly.. Thanks for coming up.

**Comment by xbblq7n** [comment]
I am using pinpoint 1.6.2 version. I have tracing an application in which the JDBC details are not getting captured.  Application is using SQL 2014 version.
