### ISSUE TITLE
 services did not display in thread?

### ISSUE THREAD

**Issue by lujs678** [naver/pinpoint#3229]
I use dubbo and code the method in a new Thread.
like this 
new Thread(new Runnable() {
    public void run{
            remoteMethod();        
    }
}).start();
But I find no dubbo service display.

**Comment by Xylus** [comment]
Hi @lujs678 
So it looks like `remoteMethod()` is invoking dubbo client call to a remote dubbo server?
If this is the case, then yes, nothing will display on the client side because a) there's no entry point in which a trace is created and b) because even if there was an entry point which created a trace, it wouldn't have propagated over to the thread that executes `remoteMethod()`.
You could instead define `remoteMethod()` as a custom entry point by setting the `profiler.entrypoint` option in *pinpoint.config*.
