### ISSUE TITLE
about the definition for the "user" request

### ISSUE THREAD

**Issue by zvrr** [naver/pinpoint#3285]
the image shows the request for the appname p-resource, but this app is the background dubbo server, the font user can't directly access the server, so what the meaning for the user such huge request? thanks.
![image](https://user-images.githubusercontent.com/194304/29800841-c8f86b46-8c9e-11e7-980b-d68e364d9bb6.png)

**Comment by Xylus** [comment]
Hi @zvrr 
Transactions from "user" node denotes requests from anywhere that does not have pinpoint agent installed. This includes browser requests, and rpcs from WASes that do not have pinpoint agent installed.
Since you've said *p-resource* is a backend api server that does not take calls directly from users, they should be from WASes that do not have pinpoint agent installed.

**Comment by zvrr** [comment]
thanks. What are the WASes could be included ?because we install  pinpoint agent for the refer app that can access  p-resource app  in our environment, so i can't find out there is another app we haven't installed.
We didn't made  pressure test for the app.

**Comment by Xylus** [comment]
They can be anything that makes rpc to *p-resource* (dubbo calls in your case?).
Oh, and calls from rpc client library not supported by pinpoint could also show up as originating from "user" node even if the application has pinpoint agent installed.

You can right-click on the arrow between *USER* node and *p-resource* node to filter transactions in a new window.
It'll take a long time to load everything since there's so many requests but you can hit pause button at the top-right and check out what these transactions are and go from there.

**Comment by zvrr** [comment]
i right-click the arrow 

![image](https://user-images.githubusercontent.com/194304/29854921-439a54b8-8d7b-11e7-8770-43c5e4597760.png)


but the new window shown data was so less than the arrow shown.

![image](https://user-images.githubusercontent.com/194304/29854914-37210b5a-8d7b-11e7-9b82-9fa4aa685ff3.png)

**Comment by Xylus** [comment]
@zvrr Yes, that is correct, If you look at the timeline (top of the second screenshot), it didn't fetch the whole thing as that would take too much time.
You can click on the *Resume* button to continue fetching if you'd like, but those transactions should be enough to give you an idea on the requests that were marked as originating from *USER*.
