### ISSUE TITLE
Hello, the value of success is inconsistent with the value of response summary. The request of user is 13466. What is the reason for this?

### ISSUE THREAD

**Issue by shijg** [naver/pinpoint#3317]
#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

![tim 20170907113949](https://user-images.githubusercontent.com/29219192/30145092-a1e6ed3c-93c1-11e7-865f-e9bdbec5763d.png)

**Comment by Xylus** [comment]
Hi @shijg 
Please check out these issues - #2381 #2423 
Thanks

**Comment by mrydy** [comment]
The scatter chart data have 1 second granularity, so the request count here can be differentiated in 1 second interval. The server map, response summary, and load chart data on the other hand, are stored in 1 minute granularity (the collector aggregates these in memory and flushes them every minute due to performance reasons). 
For more information you can click this [wiki link](https://github.com/naver/pinpoint/wiki/FAQ#request-count-in-the-scatter-chart-is-different-from-the-ones-in-response-summary-chart-why-is-this)
