### ISSUE TITLE
Plans for WildFly plugin?

### ISSUE THREAD

**Issue by andye2004** [naver/pinpoint#3440]
Just a question guys, is there any timeline on when pinpoint will work with Wildfly?

We're running Wildfly 10 and I have tried the JBoss plugin with and although everything starts there is nothing feeding through to the collector and the application name is not visible to the web component, my assumption is because the JBoss plugin is not compatible with Wildfly.

Thanks, Andy.

**Comment by Xylus** [comment]
Hi @andye2004 
We really wish we knew Wildfly well enough so that we can make a plugin for Wildfly.
Unfortunately, none of us have any experience with using Wildfly so this will not be a simple task.
Consequently, I'm not sure when we'll be able to add Wildfly support.

If you (or anyone else more experienced with Wildfly) could help out and make a Wildfly plugin and throw us a PR, it'd be wonderful!

**Comment by lk95jofr** [comment]
Hi @andye2004 
We got the agent working with wildfly 8 but not with wildfly 10.
How did you configure wildfly? Did you use domain or standalone mode?
/Regards Fredrik

**Comment by andye2004** [comment]
Hi @lk95jofr, we are using Wildfly standalone mode. As I said when I opened the ticket, the agent does not stop Wildfly from booting and applications from running, we simply don't get any results feeding through.

**Comment by lk95jofr** [comment]
We got it running with wildfly 10 when we removed Jrabel. And we see that the agent sends data to the collector, but after that it is blank. Don't know if the issue is the web can't read the data or the data is never stored in hbase
