### ISSUE TITLE
how does "agentInfo not found" occurred?

### ISSUE THREAD

**Issue by Ivan066** [naver/pinpoint#3441]
Hi,i'm delovping a plugin for a producion named "KIEV" of  my company. KIEV is developed by JAVA, and it should be a server .On my project , HTTPS requset handled by Jetty, and Jetty calls KIEV for some RPC invokes,finally KIEV link to the MYSQL .(I have tried to KIEV's serviceType to rpcClient ,but in the servermap KIEV is an rpc invoke ,  it's not my goal , because I want to see whole chains in the map )

so the chain should be : user --> jetty --> KIEV --> MYSQL.

In KIEV plugin , I have created a spanEvent to set the nextSpanid,transcationId,destinationId ,parentAppname,parentAppType and so on, then transport  span infos to the KIEV.From KIEV plugin's log, there have span info.
**KIEV SPAN:**

TSpan(
	agentId:ruipei20170911kiev1, 
	applicationName:ruipei_mzstorage_kiev1,
	agentStartTime:1508124706231, 
	transactionId:00 26 72 75 69 70 65 69 32 30 31 37 30 39 31 31 6A 65 74 74 79 C2 EF EE 99 F2 2B 07,
	spanId:2740948143996367141, 
	parentSpanId:1348812773537975530, 
	startTime:1508142506766, elapsed:16, 
	rpc:com.meizu.ratel.core.service.IAlbumFilePublicService, 
	serviceType:1960, remoteAddr:172.16.179.70, flag:0, 
	spanEventList:
		....,
	apiId:65, applicationServiceType:1000)

**and in  Jetty log, looks like it have two spans, TSpanChunk and TSpan:**
TSpanChunk(
	agentId:ruipei20170911jetty,
	applicationName:ruipei_mzstorage_jetty, 
	agentStartTime:1508124637122, 
	serviceType:0, 
	transactionId:00 01 C2 EF EE 99 F2 2B 07, 
	spanId:1348812773537975530, 
	spanEventList:[
		TSpanEvent(sequence:4, startElapsed:3, endElapsed:1, serviceType:1960, depth:5, nextSpanId:2740948143996367141, destinationId:172.16.179.72:10031, apiId:-26, asyncId:7, asyncSequence:1),
		TSpanEvent(sequence:3, startElapsed:3, endElapsed:18, serviceType:5071, depth:4, apiId:-8, asyncId:7, asyncSequence:1),
                TSpanEvent(sequence:2, startElapsed:3, endElapsed:18, serviceType:5071, depth:3, apiId:11, asyncId:7, asyncSequence:1),
		TSpanEvent(sequence:1, startElapsed:3, endElapsed:19, serviceType:9121, annotations:[TAnnotation(key:111, value:<TAnnotationValue stringValue:run>)], depth:2, apiId:-40, asyncId:7, asyncSequence:1),
		TSpanEvent(sequence:0, startElapsed:3, endElapsed:19, serviceType:100, depth:1, apiId:40, asyncId:7, asyncSequence:1)], 
	applicationServiceType:1000)

TSpan(
	agentId:ruipei20170911jetty, 
	applicationName:ruipei_mzstorage_jetty, 
	agentStartTime:1508124637122, 
	transactionId:00 01 C2 EF EE 99 F2 2B 07, 
	spanId:1348812773537975530, 
	startTime:1508142497868, 
	elapsed:25, 
	rpc:/album/check, 
	serviceType:1030, 
	endPoint:mzstorage.meizu.com:80, 
	remoteAddr:172.16.179.69, flag:0, 
	spanEventList:[
		TSpanEvent(sequence:1, startElapsed:0, serviceType:5071, depth:2, apiId:-19), 
		TSpanEvent(sequence:4, startElapsed:2, serviceType:9120, annotations:[TAnnotation(key:110, value:<TAnnotationValue stringValue:GenericCommand>)], depth:4, apiId:39, nextAsyncId:7), 
		TSpanEvent(sequence:3, startElapsed:1, endElapsed:23, serviceType:5071, depth:3, apiId:34), 
		TSpanEvent(sequence:2, startElapsed:0, endElapsed:24, serviceType:5051, apiId:-27), 
		TSpanEvent(sequence:0, startElapsed:0, endElapsed:25, serviceType:1031, annotations:[TAnnotation(key:41, value:<TAnnotationValue stringValue:userId=3000513&md5=7d5577fc73f17975aa564373d45a6969>)], depth:1, apiId:-1)],
	apiId:1, applicationServiceType:1000)

**but in the Jetty's map now:**
![jetty](https://user-images.githubusercontent.com/29398125/31603527-0b1a94c6-b293-11e7-9e2e-3dd29f4d1212.png)

**in the call tree:**
![jetty-tree](https://user-images.githubusercontent.com/29398125/31603573-277d5c70-b293-11e7-88f6-30a524ee8a20.png)

**in the KIEV's map**
![kiev](https://user-images.githubusercontent.com/29398125/31603626-4ba1cef6-b293-11e7-9369-2872a64d3dac.png)

**in the kiev's call tree:**
![kiev-tree](https://user-images.githubusercontent.com/29398125/31603660-6a1034fe-b293-11e7-8dd5-aa95f567e2ea.png)
if I set KIEV's serviceType to rpc client,the call tree is OK,but I want to show the whole chain in map.
![rpc-tree](https://user-images.githubusercontent.com/29398125/31603755-b9b3e820-b293-11e7-8760-57cc8a5022d8.png)

And now KIEV's serviceType is a server( code is :ServiceTypeFactory.of(1960, "KIEV", ServiceTypeProperty.RECORD_STATISTICS);)
**pp-web's log :**
2017-10-16 14:47:58 [INFO ](c.n.p.w.c.ScatterChartController   ) Fetch scatterData time : 17ms
2017-10-16 14:47:59 [INFO ](c.n.p.w.c.ScatterChartController   ) Fetch scatterData time : 12ms
2017-10-16 14:48:05 [INFO ](c.n.p.w.c.MapController            ) getServerMap() application:ruipei_mzstorage_jetty(STAND_ALONE:1000) range:Range{from=1508135285000, to=1508136485000, range=1200000} searchOption:SearchOption{callerSearchDepth=2, calleeSearchDepth=1}
Listening for transport dt_socket at address: 8787
2017-10-16 14:50:15 [WARN ](c.n.p.w.a.ApplicationMapBuilder    ) agentInfo not found. applicationName:172.16.179.71:10031(KIEV:1960)
2017-10-16 14:50:15 [INFO ](c.n.p.w.s.MapServiceImpl           ) ApplicationMap BuildTime: StopWatch 'ApplicationMap': running time (millis) = 129595

so the problem is:
1.Looks like pp-web recognize 172.16.179.71:10031(KIEV:1960) as an  application name,but truly the right application name is ruipei_mzstorage_kiev1(that's KIEV's application name).How does this occured？
2.What is the difference between Tspan and TSpanChunk?

Please forgive my poor English and lots of log and images.I want to see the whole chain in the Map,thanks.

**Comment by Xylus** [comment]
Hi @Ivan066 
I'm not quite sure of the internals of KIEV, but I think one of the problems is that you're using the same **ServiceType** for both **KievInvoker** (which looks like a rpc client) and **SyncBeanService** (which looks like a server acceptor).
For situations like this, you can create 2 **ServiceType**s for KIEV and use them separately (1xxx for the server acceptor part, and 9xxx for the rpc invoker part). Take a look at [Dubbo](https://github.com/naver/pinpoint/blob/master/plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/DubboConstants.java) and [Thrift](https://github.com/naver/pinpoint/blob/master/plugins/thrift/src/main/java/com/navercorp/pinpoint/plugin/thrift/ThriftConstants.java) plugins as they work similarly.

Also, please make sure you have built and deployed your pinpoint collector and web with the KIEV plugin included.

As for your questions,
1. It's because the **destinationId** in Jetty's KIEV rpc call span event (`172.16.179.72:10031`) does not match **acceptorHost** in KIEV's span (none above). Please refer to [this](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide#222-continue-transaction) (server) and [this](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide#23-methods-invoking-a-remote-node) (client) for more info.
2. You can think of **TSpanChunk**s as **TSpan** split into chunks. Since **TSpan** contains **TSpanEvent**s and these can grow very large, instead of holding everything in memory until the span completes, we send off some span events early in the form of **TSpanChunk**s.

Let me know if you've more questions.
Thanks!

**Comment by Ivan066** [comment]
@Xylus Thanks very much for your reply .I've solved this problem! Here are the solutions:
1. As your advice,  I have created 2 ServiceTypes for KIEV and use them separately ,just like Dubbo
.In KievInvoker , the serviceType is KIEV_CLIENT , and in  SyncBeanService , serviceType is KIEV_SERVER.
2.It's my mistake that I forgot to set endPoint value in KievInvoker.Now map and call tree both works.
