### ISSUE TITLE
There is no data when monitoring a jar file

### ISSUE THREAD

**Issue by egozkan** [naver/pinpoint#3451]
Hi,
i want to monitor a jar file but there is no data for this jar. What should i type for **profiler.applicationservertype** parameter? or is problem at another place?

**Environment:**
OS: CentOS 7 
pinpoint agent version: 1.6.2

**Additional Info:**
I ran network.sh script, all output has success:

UDP-STAT:// 10.1.3.132
    => 10.1.3.132:9995 [SUCCESS]

UDP-SPAN:// 10.1.3.132
    => 10.1.3.132:9996 [SUCCESS]

TCP:// 10.1.3.132
    => 10.1.3.132:9994 [SUCCESS]

thanks

**Comment by Xylus** [comment]
Hi @egozkan 
In order for pinpoint to start tracing, it needs an entry point that will create a span (which starts off a trace). This is normally done by various WAS plugins where they'll start a new trace when they receive a rpc request.
Since you're monitoring a custom jar file, the agent probably does not have an entry point as it won't have any knowledge of when and where to start a new trace.
You can set custom entry points in *pinpoint.config* by defining the `profiler.entrypoint` option (https://github.com/naver/pinpoint/wiki/FAQ#my-custom-jar-application-is-not-being-traced-help).
