### ISSUE TITLE
hello,pinpoint Can you get the real IP address of the client?

### ISSUE THREAD

**Issue by hanrongsu** [naver/pinpoint#3500]
hi,
pinpoint Can you get the real IP address of the client? In the case of F5 and other hardware to do load balancing.

**Comment by koo-taejin** [comment]
hi hanrongsu

If your load balancer has the function  to change to real IP and forward it, you can use it.
Otherwise, you can use *.realipheader( profiler.tomcat.realipheader, profiler.jboss.realipheader, ... ) configuration in pinpoint.config.
If you use this configuration, must include client IP in the header when sending from client.

thanks.

**Comment by hanrongsu** [comment]
thank you for reply.
