### ISSUE TITLE
Additional data transformation in HBase, why? 

### ISSUE THREAD

**Issue by ecamy** [naver/pinpoint#3509]
#### Description

When I look into the data in HBase,  I see additional transformation from rowkeys to values , why?  That takes some difficulties for me to utilize the monitoring data. I also study the class related , but fell that it is hard to debug from the front and the back  of pinpoint, Would you tell me how to parse them? 

Thanks so much.

#### Environment
pinpoint-1.6.1
HBase-1.0.3

Develop environment: win8+ eclipse+ jdk6-7-8
Test environment: CentOs6.5

**Comment by Xylus** [comment]
Hi @ecamy 
Due to the way hbase scans data, the row keys are often serialized after concatenating more than 1 "attribute" (ie agent id + start timestamp). These keys are also often prefixed with a hash byte (or more) to ensure a balanced region distribution.
This is why it's hard to see the row keys in as a human-readable plain-text.

I would recommend you utilize the hbase mappers if you're trying to make sense of data stored in hbase.

**Comment by liyang8** [comment]
Hi @Xylus 
```java
buf[offset++] = (byte) (value >> 56);
buf[offset++] = (byte) (value >> 48);
buf[offset++] = (byte) (value >> 40);
buf[offset++] = (byte) (value >> 32);
buf[offset++] = (byte) (value >> 24);
buf[offset++] = (byte) (value >> 16);
buf[offset++] = (byte) (value >> 8);
buf[offset++] = (byte) (value);
```
I do not understand this code, Why should the reverse of the timestamp and then bit operation？

**Comment by ecamy** [comment]
A great design. Thanks for your guiding.
