### ISSUE TITLE
applications.pinpoint Request running endless

### ISSUE THREAD

**Issue by csanderlg** [naver/pinpoint#354]
Hi,

I just trying to bring up 1.0.4. Everthing seems to be fine and as I can trust the log the Collector ist collecting data ;)

But in Pinpoint Web, I'm not able to select an Application.
When I try to debug it, I see that the following request is running endless: http://XXX.XXX.XXX.XXX:8080/applications.pinpoint

Can you help me?

THX and greetings form Germany

Carsten

**Comment by nstopkimsk** [comment]
Hi csanderlg,

Could you give us more logs ?

**Comment by csanderlg** [comment]
Hi,

I found this one in the log:

04-21 12:46:30 [WARN ](c.n.p.c.h.AgentStatHandler         :61) AgentStat handle error. Caused:Unable to find region for AgentStat,,99999999999999 after 14 tries.; nested exception is org.apache.hadoop.hbase.client.NoServerForRegionException: Unable to find region for AgentStat,,99999999999999 after 14 tries.; nested exception is org.springframework.data.hadoop.hbase.HbaseSystemException: Unable to find region for AgentStat,,99999999999999 after 14 tries.; nested exception is org.apache.hadoop.hbase.client.NoServerForRegionException: Unable to find region for AgentStat,,99999999999999 after 14 tries.
 
kind regards

**Comment by Xylus** [comment]
Hi csanderlg, it seems like there's a problem with one of your region servers.
Could you check if they're all online? (you can check them at hbase_master:60010)

It could also be due to hbase version - which version of hbase are you running? We've only tested Pinpoint against 0.94.x so this could be the issue.

Regards

**Comment by Xylus** [comment]
Got some input from @minwoo-jung as well.
The error log is due to the Web not being able to connect to the region server.
You'll need to add hbase region server domain info to the hosts files in the machines running Pinpoint Collector and Web.

We believe our documentation on setting up the environment for Pinpoint is a bit lacking. We're working on releasing a guide to help this out soon so please stay tuned =)

Thank you.

**Comment by csanderlg** [comment]
Hi Xylus,

changed the Setup to hbase 0.94.x. 
Now it is Working ;)

Thx for your support.
