### ISSUE TITLE
spring boot application not display database.

### ISSUE THREAD

**Issue by chanwu79** [naver/pinpoint#3555]
spring boot application not display database .my application connect postgresql.
![image](https://user-images.githubusercontent.com/33505058/32872144-1f7714c2-cac0-11e7-952d-ce14d86c6851.png)

**Comment by Xylus** [comment]
Closing due to lack of detail - please read https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md#issues
Please reopen once you have explained your issue with a bit more detail.
A few things to consider : 
* You haven't made any requests to the application (or it hasn't been traced), so the database could not have been displayed anyway.
* Please describe your spring boot application. Is it serving tomcat servlets? Jetty? or is it just a plain java application?
* Check the agent start up log and if everything seems okay, share it if possible so that we can take a look.
