### ISSUE TITLE
Question of Asynchronous_Trace

### ISSUE THREAD

**Issue by Super4You** [naver/pinpoint#3569]
Hello,When develop pinpoint plugin for  an asynchronous framework of myself company, met some  problems.The received request thead generate AsyncTraceId through the **Scope** to  passed to the business thread,so that across threads, as shown in screenshot:

**Public InterceptorScopeInvocation getCurrentInvocation () {
    Return a threadLocal. The get ();
}**

This method use threadLocal to store the **AsyncTraceId**, while the Scope is global, but in business thread **InterceptorScopeInvocation** is unable to get the asyncTraceId , so  that business thread will be called the **initialValue()** method to generate a  new **InterceptorScopeInvocation** object, business threads will not get the **AsyncTraceId**, could you tell me the problem is that I lost what details,  looking forward to your reply!

![1](https://user-images.githubusercontent.com/25604732/32965659-2081dcd2-cc12-11e7-9c5a-c8d71b326644.png)
![2](https://user-images.githubusercontent.com/25604732/32965660-21052c9a-cc12-11e7-873e-9bdbeee17d31.png)

**Comment by Xylus** [comment]
Hi @Super4You 
If I'm understanding your issue correctly, I think you're mixing up **InterceptorScope** and trace propagation over thread boundary.
For propagating trace over thread boundary, all you need to do is inject **AsyncTraceId** into an object that's passed over to another thread
(for example, `((AsyncTraceIdAccessor) object)._$PINPOINT$_setAsyncTraceId(asyncTraceId);`).

Going by the the [_12_Asynchronous_Trace](https://github.com/naver/pinpoint-plugin-sample/tree/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_12_Asynchronous_Trace) example,
```
public class TargetClass12_AsyncInitiator {
    
    public TargetClass12_Future asyncHello(String name) {                           // [Thread-1] AsyncInitiatorInterceptor creates AsyncTraceId and sets it to Thread-1's thread local via InterceptorScopeInvocation..
        TargetClass12_Future future = new TargetClass12_Future();
        TargetClass12_Worker worker = new TargetClass12_Worker(name, future);       // [Thread-1] WorkerConstructorInterceptor retrieves the AsyncTraceId from thread local and injects it into "this" TargetClass12_Worker instance.
        
        new Thread(worker).start();
                                                                                    // [Thread-2] When worker.run() is invoked, WorkerRunInterceptor (child of SpanAsyncEventSimpleAroundInterceptor) retrieves the AsyncTraceId from "this" TargetClass12_Worker instance and uses it to continue tracing.
        return future;
    }
}
```

So in your case, instead of using **Scope** to pass **AsyncTraceId** over to the business thread, your request thread should instead inject **AsyncTraceId** into an object that will be passed on over to the business thread.

Please feel free to ask any more questions.
Thanks

**Comment by Super4You** [comment]
Although the existing code is different from the provided case, I have successfully solved the asynchronous problem under your guidance. I,m mixing up InterceptorScope and trace propagation over thread boundary at first.Thank you very much.

**Comment by Xylus** [comment]
:+1:
