### ISSUE TITLE
PermGen Usage max collect error

### ISSUE THREAD

**Issue by iicanf** [naver/pinpoint#3635]
#### Description

hi @Xylus ，our pinpoint work well but the PermGen Usage。Am i miss some config？
![2017-12-14_173953](https://user-images.githubusercontent.com/2391122/33985955-0e867d18-e0f7-11e7-94f5-94bcbb07a16e.png)
the message when i debug:
![2017-12-14_174221](https://user-images.githubusercontent.com/2391122/33985979-20fe40c0-e0f7-11e7-847c-c192792c6c89.png)

#### Environment

* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc: win10 （also ubuntu 14.04）
* Additional details (e.g. how your collector/web is set up): tomcat 8，jdk 8 ,tomcat
with the follow set in catalina.bat:
```
set CATALINA_OPTS=-Xms1536m -Xmx1536m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m
````
waiting for you reply.

**Comment by Xylus** [comment]
Hi @iicanf 
Perm gen is removed in java 8 and is replaced by metaspace.
(The chart title is *PermGen Usage* still and it might be misleading, and we should probably fix that)

I think the reason why the agent is not collecting non-heap max and the chart isn't showing them is because metaspace max has not been set. Try setting it using `-XX:MaxMetaspaceSize`.

**Comment by iicanf** [comment]
@Xylus 
thanks a lot, after set `-XX:MaxMetaspaceSize` the chart, the max can collect normal. how about directly replace the name from *PermGen Usage* to *Non Heap Usage*.
