### ISSUE TITLE
Clarification on running Flink Streaming job for ApplicationStatAggergation feature 

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3636]
Hi Team,

I would like to run Pinpoint flink stream job to leverage the ApplicationStatAggregation in 1.7.0, Currently i would need to understand the following things for setting up the same 

Clarifications:

1) Which version of Flink jar we need to use for running the streaming job (pinpoint-flink-job-2.0.jar)

2) Can i use the latest version of flink-1.4.0 - link - https://archive.apache.org/dist/flink/flink-1.4.0/flink-1.4.0-src.tgz

3) Do we need separate Zookeeper server for running the flink job or we can use the zookeeper which already being available in the design for sending data to Hbase 

4) How do we manage and scale the flink cluster, lets I might be hitting around 1000 TPS maximum from all the agents and how do we really design the capacity of flink server nodes 

5) I am using jdk8 and hope it is fine for running the stream jobs

Let me know If I have misinterpreted anything here

**Comment by minwoo-jung** [comment]
I got it. I will reply on you sooner or later.

**Comment by minwoo-jung** [comment]
1.Which version of Flink jar we need to use for running the streaming job (pinpoint-flink-job-2.0.jar)
- **We recommend the flink 1.3.1 version**

2.Can i use the latest version of flink-1.4.0 - link - https://archive.apache.org/dist/flink/flink-1.4.0/flink-1.4.0-src.tgz

- **We only test and use flink 1.3.1 version. I don't know how exactly, I expected flink 1.4.0 version is ok.1.4.0. But you would try to test it by using flink 1.4.1 for yourself.**

3.Do we need separate Zookeeper server for running the flink job or we can use the zookeeper which already being available in the design for sending data to Hbase
**It doesn’t matter which zookeeper you use. Because utilization of the zookeeper is low by flink job.**


4.How do we manage and scale the flink cluster, lets I might be hitting around 1000 TPS maximum from all the agents and how do we really design the capacity of flink server nodes
- **Maybe you don't worry network. At first you execute singleton and montoring. And you [confiure option](https://ci.apache.org/projects/flink/flink-docs-release-1.4/ops/config.html). If it need to more resource, you should set flink cluster.**
	

5.I am using jdk8 and hope it is fine for running the stream jobs
- **Ok, You can use jdk8, We use it too.**

**Comment by adventurer2008** [comment]
1.Which version of Flink jar we need to use for running the streaming job (pinpoint-flink-job-2.0.jar)

    We recommend the flink 1.3.1 version


**I tried the flink 1.4.0 version. But it can't work. flink 1.3.1 version is ok.  But we need to set flink.StreamExecutionEnvironment to remote for pinpoint-flink.properties and it's not described under the official documents.**

**Comment by minwoo-jung** [comment]
@adventurer2008 Hello~ Thank you for pointing out guide. 

I will add guide for configuration soon.

First of all, please this guide.

```
# flink env init
flink.StreamExecutionEnvironment=server
flink.sourceFunction.Parallel=1 #set as flink server count
```

I appreciate it.^^

**Comment by minwoo-jung** [comment]
I added guide for [flink env init configuration](https://github.com/naver/pinpoint/blob/master/doc/application-inspector.md#3-configuration)

**Comment by zhangzhaoyu** [comment]
Hi, I used flink-1.4.0 to run the pinpoint-flink-job-2.0.jar. I get the wrong message below.

> 2018-01-29 16:16:34,787 WARN  org.springframework.context.support.ClassPathXmlApplicationContext  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverAcceptor' defined in class path resource [applicationContext-flink.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.jboss.netty.util.HashedWheelTimer.<init>(Ljava/util/concurrent/ThreadFactory;Lorg/jboss/netty/util/ThreadNameDeterminer;JLjava/util/concurrent/TimeUnit;I)V

I think the problem is that pinpoint-flink used netty-3.x, but flink-1.4 used netty-4.x. Like those classes **FlinkServerRegister**, **PinpointServerAcceptor**.

I want to know will you support flink-1.4.x in the feature?  @minwoo-jung

**Comment by minwoo-jung** [comment]
Ok I should check.

**Comment by minwoo-jung** [comment]
@zhangzhaoyu 
I recommend use flink 1.3.1 version. But if you want to use 1.4.1 by Changing dependency, You should check side effect.
We don't have any plans yet to change flink version.

**Comment by minwoo-jung** [comment]
@zhangzhaoyu @dinesh4747

Sorry for late reply.
I have looked at issue and I found the cause. I talk the solution.
**Please use flink 1.5 and later versions.**

**detailed explanation**
It is related to https://issues.apache.org/jira/browse/FLINK-8668.
- commit code : https://github.com/apache/flink/commit/9d5a7857ffb758f2dd04556b91038e9d5ca51939#diff-731c5617b8cd8d379471eb14537d2767

It can happen when hadoop was installed in flink server. 
Because flink's classpath contains hadoop classpath, org.jboss.netty.util.HashedWheelTimer class was loaded at netty library in hadoop path.
If you want to check exact location, use java option -verbose:class.

If this does not resolve the issue, tell me about that. 
I'll look into it with you.^^

**Comment by minwoo-jung** [comment]
This issue is related to [hadoop-classpath-discovery](https://ci.apache.org/projects/flink/flink-docs-release-1.5/release-notes/flink-1.5.html#hadoop-classpath-discovery)
