### ISSUE TITLE
UdpDataSender issue

### ISSUE THREAD

**Issue by gaoyf** [naver/pinpoint#3658]
First, I'm glad to read some source code of pinpoint,  it's High-Quality and Great-Design.
But I feel uncertain about the behavior of `SpanDataSender ` in some situation.
By default `SpanDataSender ` use UDP protocol, Some source code fragment of `UdpDataSender` is bellow: 
```
DatagramSocket datagramSocket = new DatagramSocket()
InetSocketAddress serverAddress = new InetSocketAddress(host, port);
datagramSocket.connect(serverAddress);
```
The parameter **host** can be domain name and domain name will be translated into ip list by DNS finnally. So DatagramSocket will connect to a real ip actually.
**If the ip list of domain name change, the socket should reconnect to the new ip.**
But there is no any reconnection logic. In other words, i need to restart all of applications if the ip list changed! And I find `DefaultPinpointClientFactory` has the reconnection logic, but it uses TCP protocol with NETTY. I prefer to use UDP protocol.
**So should `UdpDataSender` need add the reconnection logic in the future?** Thx!
Below is my  logic deployment:

![123](https://user-images.githubusercontent.com/10137071/34399808-06a525e8-ebc6-11e7-96af-21ce24222211.png)

**Comment by koo-taejin** [comment]
hi gaoyf

I understand it, and thank you for giving me a good opinion.
It seems that has potential risk for datagram reconnect part.
 
In fact, the goal of UDPSocket's address management is to have its own load balancing function by interworking with TCPSocket.
However, we do not have plan yet.
If this goal will complete. it will be a solution to this problem.

If you are currently facing this problem, then use tcp instead of udp then the problem will not occur. (#3275)
Before developing the above functions, i will consider simple solution to this part.
Thank you again for your good feedback.

thanks.

**Comment by emeroad** [comment]
The current version of pinpoint is L4 based design.
Changing IP of the load balancer is not recommended.

**Comment by gaoyf** [comment]
I will try to use tcp after 1.7.0 releasing!
Thank you for your response quickly! @koo-taejin @emeroad

**Comment by koo-taejin** [comment]
To avoid this issue, you should change the jre's dns cache configuration before changing to tcp.
please refer to this link (https://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html)\

**Comment by gaoyf** [comment]
Thank you for your reminding.
