### ISSUE TITLE
SQL can't be traced, why?

### ISSUE THREAD

**Issue by ecamy** [naver/pinpoint#3684]
#### Description
Hi,
When we monitored our system using pinpoint, we can't see our mysql database on the main web, and also can't see sql statements of program in call stack, would you help me?

#### Environment

* Pinpoint version: 1.7.0
* Windows8 + Hbase1.2.6 
* ibase4j Framework+ Druid connect pool + Mysql database

**Comment by koo-taejin** [comment]
hi ecamy 

We are not familliar with your environment. (ibase4j or druid etc.)
There are a variety of reasons why mysql is not visible.
Access to mysql in an untraceable scope or using connectors that we do not support or etc..
With the information you gave us, we do not know the cause of the problem.

I ask you to analyze you're application and find out what causes it to be related first.
Post a log of what you think is relevant to the problem.t.
Otherwise, it is difficult for us to help.

thanks.

**Comment by ecamy** [comment]
Thanks. It's a pity that the log just was deleted two days ago. I will pay attention to keep them next time.
