### ISSUE TITLE
How to display the argments in the web

### ISSUE THREAD

**Issue by yangliang003** [naver/pinpoint#3736]
Hi,
   How to display the values of the params in the web ? I can't find counfig related to this.Does pinpoint 
 teams have a plan on this?Thanks.

the screenshot:
![20180119](https://user-images.githubusercontent.com/16607114/35200910-b501ce14-ff50-11e7-9deb-b2ac63a4f694.png)

**Comment by Xylus** [comment]
Hi @yangliang003 
Are those methods traced via user plugin? Or did you develop a custom plugin to trace those methods?
If they're via the user plugin, the user plugin doesn't trace method arguments as we don't know what's going to be there.
If you've made a custom plugin, please take a look at [this](https://github.com/naver/pinpoint-plugin-sample/blob/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_02_Injecting_Custom_Interceptor/RecordArgsAndReturnValueInterceptor.java) plugin sample to record method arguments in the interceptor.

**Comment by yangliang003** [comment]
@Xylus Thanks！I  trace it though the user plugin，I just modify the profiler.include.Is it means
 that we only could get the custom methods's param through the user plugin? Thanks

**Comment by Xylus** [comment]
@yangliang003 Thank you for your suggestion. We can't have the user plugin trace arguments automatically because we don't know what kind of argument we'll be tracing.
We can't simply call `toString` on arguments - some wouldn't have `toString` implemented so the information would be useless, and some might even have very heavy `toString` implementations (huge collections?).
So it'd be too dangerous to trace arbitrary arguments.
