### ISSUE TITLE
Error:Host Name must not be null

### ISSUE THREAD

**Issue by Super4You** [naver/pinpoint#3751]
Hello,In the case of the use of pinpoint and the plugin is developed for the company's own application. Recently, the error in the screenshot of the pinpoint-web is often shown. When the Inbound and Outbound Settings are 1-2, the query time period is within 5 minutes to 1 hour (shorter than the present interval). The page can be displayed normally, but when the Inbound and Outbound Settings are 4, or the plugin time is set to 2day, this error will occur.Is there a problem to the development of plugin that Agent into the data has a problem, or what causes?
![1111](https://user-images.githubusercontent.com/25604732/35318139-05ec7c64-0115-11e8-9945-bf40b10d6e7e.png)

**Comment by Xylus** [comment]
Hi @Super4You 
Without access to your plugin's code, or the collector log, it's hard to pin down what exactly could have caused this.

But from just looking at the error above, the NPE is thrown because the hostname is not stored in hbase (or is empty), which should happen if your plugin doesn't call `SpanRecorder.recordEndPoint(...)`, or if an empty string is passed as an argument to that method. I would suggest taking a look at your plugin's interceptor code and compare it against [this](https://github.com/naver/pinpoint-plugin-sample/blob/master/plugin/src/main/java/com/navercorp/pinpoint/plugin/sample/_14_RPC_Server/ProcessInterceptor.java#L85) sample.

Additionally, since this only happens when you query for inbound/outbound depth > 1, or over a long period of time, even if your plugin currently recording the endPoint, you should also check if any past versions of the agent without the code above is being used.
