### ISSUE TITLE
anonymous class question

### ISSUE THREAD

**Issue by iicanf** [naver/pinpoint#3773]
#### Description

@Xylus just a little question, can pinpoint trace the `onCompleted` and the method after it ?

        import org.asynchttpclient.*;
        import java.util.concurrent.Future;

        AsyncHttpClient asyncHttpClient = new DefaultAsyncHttpClient();
        asyncHttpClient.prepareGet("http://www.example.com/").execute(new AsyncCompletionHandler<Response>(){
            
            @Override
            public Response onCompleted(Response response) throws Exception{
                // Do something with the Response
                // ...
                return response;
            }
            
            @Override
            public void onThrowable(Throwable t){
                // Something wrong happened.
            }
        });

#### Environment

* Pinpoint version: 1.6.2
* library: https://github.com/AsyncHttpClient/async-http-client/tree/async-http-client-project-2.0.24

**Comment by Xylus** [comment]
Hi @iicanf 
It's possible, but it's not as simple as simply adding basic method interceptors to `onCompleted()` and `onThrowable()` methods.
This is because the thread (let's call it execution thread) that invokes those methods is not the same as the calling thread that has the trace object, so you'll have to pass the trace object over to the execution thread from the calling thread via a shared object (such as **AsyncCompletionHandler**).

You'll then have to have the interceptors for `onCompleted()` and `onThrowable()`, or for a upper level method that has both these methods in it's scope, to retrieve the trace object and continue tracing.

For more information about tracing asynchronous calls, please check out [this guide](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide#24-asynchronous-task).
