### ISSUE TITLE
Load and Summary Charts on the Application Dashboard

### ISSUE THREAD

**Issue by ashidhull** [naver/pinpoint#3803]
#### Description
The Load and Response charts seem to be confusing to understand
**Load Chart:**

- Shouldnt the load chart be depicting Transactions/Second? The inspector shows the view but its confusing to have the Load chart on the main Screen doing that

- Should the Load chart need to have response time on it?

**Response Summary:**

- Shouldnt the response summary chart be timeseries rather than just showing amount of transactions under certain time bound?

Please let me know if we can discuss the intent of the charts on the main screen
![pinpoint_scatter_chart 20180205_1041_20180205_1046](https://user-images.githubusercontent.com/3771685/35829755-8a242478-0a89-11e8-87b9-587bb4261855.png)

#### Environment

* Pinpoint version:
* OS, WAS, affected library, etc:
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

![image](https://user-images.githubusercontent.com/3771685/35829814-b4dbea70-0a89-11e8-868f-519706a703e0.png)

**Comment by Xylus** [comment]
Hi @ashidhull 
Thanks for laying out the issue in detail.
Hope my answer below clears up some of your confusion.

**Load Chart**
**Load** is, I think we both agree, some number of work (transactions in this case) over a given time frame. So the load chart is effectively the same thing as transactions/second, just with different time frame (transactions/minute in the picture above). Showing response time on it is simply adding another dimension to the chart because it's useful and does not take anything away from the chart.
That said, the difference with the tps chart in the inspector view is that the load chart shows only the number of **sampled** transactions whereas the tps chart shows **unsampled** transactions as well. So we do have plans to bring the tps chart into the server map view in the future.

**Response Summary**
Response Summary chart provides a summary of response times for the queried time interval. If it is changed to a time series chart, it would look exactly the same as the load chart.
