### ISSUE TITLE
throw exception bug in JBOSS plugin

### ISSUE THREAD

**Issue by chenjienn** [naver/pinpoint#3817]
#### Description

I run a simple web demo in jboss , then throw an exception in my custom servlet on purpose (such as NoSuchBeanException in Spring) .  But the StandardHostValveInvokerInterceptor can not recognize such exception , cause the exception has been encapsulated into the org.apache.catalina.connector.Request. 

I have to add bellow code to extract the exception : 

    @Override
    public void after(final Object target, final Object[] args, final Object result, Throwable throwable) {
        for (Object arg : args) {
            if (arg instanceof Request) {
                Request request = (Request) arg;
                Throwable t = (Throwable)request.getAttribute("javax.servlet.error.exception");
                if (t != null) {
                    throwable = t;
                }
            }
        }

**Comment by emeroad** [comment]
The manipulation of the control flow in the interceptor is not possible.
Manipulating the control flow is potentially dangerous to security
There is no plan to provide it in the future.

**Comment by chenjienn** [comment]
That mean pinpoint ignore such exception ?

**Comment by BenGAO** [comment]
@emeroad 

In the servlet, the following:

protected void doGet(HttpServletRequest request,HttpServletResponse response) throws ServletException,IOException {
dosomething();
throw new ServletException("something error");
}
The pinpoint web display is a successful call.In fact, the background has gone wrong and should be a failed call.

**Comment by emeroad** [comment]
To display the error status on the display, we recommend using `SpanRecorder.recordException()` or `SpanRecorder.recordError()` API

**Comment by Xylus** [comment]
Hi @chenjienn @BenGAO 
The exception thrown by your custom servlet is caught and handled before reaching `StandardHostValve.invoke(...)`, so no exception is recorded in **StandardHostValveInvokeInterceptor**.
This is why we have **SpringWebMvcPlugin** providing the [necessary interceptor](https://github.com/naver/pinpoint/blob/master/plugins/spring/src/main/java/com/navercorp/pinpoint/plugin/spring/web/SpringWebMvcPlugin.java) to record exceptions thrown at the servlet level.

If you have a custom servlet that you want to trace, you can configure your servlet's `doGet` and `doPost` (and possibly other methods of interest) using *profiler.entrypoint* in *pinpoint.config* file so that it'll record exceptions before they are caught and handled.
