### ISSUE TITLE
how to trace  http request parameter of tomcat ?

### ISSUE THREAD

**Issue by kingtiger2** [naver/pinpoint#3957]
#### Description
i want to see http request parameter in call tree ,for example:json  string
#### Environment
tomcat
pinpoint:1.7.0-rc2

**Comment by RoySRose** [comment]
Install Pinpoint and run Pinpoint-Agent with your application.
You can check the call stack to find what you are looking for. Screen is displayed like [this](http://naver.github.io/pinpoint/overview.html#overview)

**Comment by orientzc** [comment]
i think it can only trace data of Get. if i want to see http request/response body, what can i do?
thanks
@RoySRose

**Comment by RoySRose** [comment]
Hello @orientzc 
Currently, as you have pointed out, Pinpoint doesn't show the data that you have mentioned.
If you really need the information on this, By utilizing [this feature](https://naver.github.io/pinpoint/perrequestfeatureguide.html),
and little more programming on recording the data(distinguished with transactionID) in the log.
You will be able to see the information on it.

**Comment by orientzc** [comment]
Thanks a lot. @RoySRose 
but this solution will be need to intrusive code. as you have said, i must record the data in the log in my project. for example,
logger.info("request.body:"+requestBody) or logger.info("response.body:"+responseBody)
is that what I am to understand? what do i miss?
i want to record the data by "middleware" instead of log. because it is a comman module for every project. Thanks for your help. and is it a better way to solve it? Thanks.

**Comment by RoySRose** [comment]
@orientzc 

Well, this isn't a simple way, but you can develop a plug-in for Pinpoint to record HTTP request parameter of tomcat in the log. If you wish to take a look regarding this, here is [plug-in development guide.](http://naver.github.io/pinpoint/plugindevguide.html) This way you don't have to create any intrusive code inside your project.

Pinpoint doesn't collect HTTP request parameter data, because its data size may be too large and currently we don't yet have any plans to support it. But I'll mention this issue up to the team.

**Comment by orientzc** [comment]
@RoySRose 
Thanks a lot. i wil try to develop a plugin. Good luck for me.

**Comment by RoySRose** [comment]
@orientzc Good Luck:)

As I have said, we don't yet have any plans to support it.
If you can make a plugin with a disabling option. It will be great!

**Comment by liuchuan1992** [comment]
i am wonder if pinpoint can record the request parameters,not just http request body, also can be RPC request

**Comment by RoySRose** [comment]
Hello @liuchuan1992 
No plans have changed since this question has arisen.

**Comment by liuchuan1992** [comment]
thanks @RoySRose .
and I hava a question about this .
Pinpoint doesnot suppoort it because Javaagent cannot support recording request params or actually it can support  ,just considering the request params are too large to store

**Comment by RoySRose** [comment]
@liuchuan1992 
Well, as I've noted earlier, it's due to it's size.
```
Pinpoint doesn't collect HTTP request parameter data, because its data size may be too large and currently we don't yet have any plans to support it. But I'll mention this issue up to the team.
```
Afterall, what can be impossible in programming? :)

**Comment by liuchuan1992** [comment]
@RoySRose  haha~  thanks very much
