### ISSUE TITLE
Pinpoint not connecting to Jboss

### ISSUE THREAD

**Issue by ajaysoft2003** [naver/pinpoint#4003]
#### Description
Pinpoint collector and web is installed on apache tomcat of windows
hbase is installed on linux
agent is installed on jboss and all jboss parameters are set as per documentation. 
Agent is not connected to collector/web. No log is coming in Jboss. 
There is no log folder under pinpoint agent. 

Questions are as follows
1. where to look for to refer any log. Server.log of jboss is not giving any log about pinpoint. there is no log folder under /opt/pinpoint

2. is it necessary to enable the zookeeper? I have kept "cluster.enable=false" to disable zookeeper.

3. is it necessary to keep udp and tcp port both open? I have opened up TCP port between collector and agent

####Environment
pinpoint is 1.7.1 and installed on windows server 2012
tomcat is 8.5.27. 
jboss standalone 6.4
hbase installed on linux

**Comment by ing-arriola** [comment]
In my case I install hadoop, hbase and pinpoint in the same machine with ubuntu 16.04, separating hadoop and hbase from Pinpoint in my opinion implies that you must understand in depth the architecture of HBase and Hadoop as well as the way in which they communicate with Pinpoint. I recommend the following installation videos of Hbase and Hadoop. I followed them and then installed Pinpoint, everything worked excellent for me.
I hope the information is helpful to you.
HADOOP:
https://www.youtube.com/watch?v=l1QmEPEAems&t=671s
HBASE:
https://www.youtube.com/watch?v=zK39o0TMzFo&t=116s

**Comment by ajaysoft2003** [comment]
Thanks bu My question is not about hbase, my question is wether pinpoint uses zookeeper to communicate everything between agent and collector? Is zookeeper mandatory or can pinpoint work without zookeeper

**Comment by koo-taejin** [comment]
hi ajaysoft2003 

Hbase use zookeeper. That's why you must have a zookeeper.
(However, if hbase is used as standalone, it looks like it does not use zookeeper from outside because it uses internal zookeeper.)

Therefore, the addresses of `hbase.client.host` and` hbase.client.port` in hbase.properties can be used for `cluster.zookeeper.address`.

Addtionnally `cluster.enable = false` This configuration is to use zookeeper.
This part does not have to be true. 
If the option is false, the active thread chart can not be excuted.

thanks.

**Comment by ajaysoft2003** [comment]
Thanks. ..where to look for agent log. After doing all the settings, jboss agent is still not connected.
