### ISSUE TITLE
Some questions about the UI

### ISSUE THREAD

**Issue by JackeyLee007** [naver/pinpoint#4024]
What does the "WAS only" mean?
Why the "Inbound" and "Outbound" are limited smaller than 4?
And what does ths points mean in the red circle of the following picture?
![image](https://user-images.githubusercontent.com/1195708/38777065-611c19ec-40d4-11e8-8ac7-8d0d4efef563.png)

**Comment by Xylus** [comment]
Hi @JackeyLee007 

Selecting **WAS only** removes terminal nodes such as database, cache or unknown rpc nodes from the server map. It might be helpful to select when you have too many such nodes cluttering up the server map.

Inbound and outbound are limited to 4 currently because of complex server maps may be too large with 4 depth. However, this might change in the future with more optimization.

The red circle's description is under the help menu on the top right corner of the screen.
> Renders inbound/outbound nodes for each and every node (within limit) even if they are not directly related to the selected node.
Note that checking this option may lead to overly complex server maps.

**Comment by JackeyLee007** [comment]
Hi @Xylus,

That's clear! Thanks for your answer.

Regards
