### ISSUE TITLE
A fast auto pinpoint agent plugin generate tool,How to contributing this tool to pinpoint?

### ISSUE THREAD

**Issue by yin-bp** [naver/pinpoint#4177]
I write A fast auto pinpoint agent plugin generate tool,How to contributing this tool to pinpoint?

Here is the tool:
https://github.com/bbossgroups/pinpoint-plugin-generate

**Comment by RoySRose** [comment]
Hello, @yin-bp 
First of all, Thank you for your interest and the contribution to the Pinpoint Community.

I've gone through your project on plugin-auto-generator.
It's great! I think it would be perfect for the ones who need their application monitored but having a hard time understanding the instrumentation methodology or the architecture of the plug-ins for the Pinpoint.

I am still trying to think of better ways for your suggestions. 
Since [Pinpoint GitHub page](https://github.com/naver/pinpoint) only contains source to Pinpoint,
So far I've come up with is as below.

1. We can insert LINKs to your github repository from our [Official Homepage](https://naver.github.io/pinpoint/plugindevguide.html)
2. Pinpoint sub tools are under another repository such as [naver/pinpoint-docker](https://github.com/naver/pinpoint-docker), [naver/pinpoint-plugin-template](https://github.com/naver/pinpoint-plugin-template). But since all sub tools are created by us and we've never had this kind of contribution from the community, I'm not even sure this is possible. I'll check on this, if you really want to continue this way and making it official sub repository.
3. Open for your suggestion:)!!

@yin-bp, waiting for your suggestion:)

**Comment by yin-bp** [comment]
Hi,Thank you for your comments.Here is my suggestion:
- First
 Insert a link of  [pinpoint-plugin-generate](https://github.com/bbossgroups/pinpoint-plugin-generate)  Github repository to pinpoint's  [Official Homepage](https://naver.github.io/pinpoint/plugindevguide.html)
- Then 
If  making it official sub-repository is  possible, I am very willing to do this work.
That's all,Thanks.

**Comment by RoySRose** [comment]
Hello, @yin-bp 

The link has been added to the [plugin dev guide](https://naver.github.io/pinpoint/plugindevguide.html)

Thank you for your interest in the Pinpoint Community.
Have a nice day :)
