### ISSUE TITLE
deploy hbase on another server,which file did i modify?

### ISSUE THREAD

**Issue by Rnic** [naver/pinpoint#4213]
hi, i have 3 servers to deploy pinpoint
 server1 :  i deployed hbase
 server2:   i  deployed collector and web
 server3:   i deployed  agent on it which in  a testAPP
 
before started collector and web , i had change hbase.properties
hbase.client.host=server1ip
hbase.client.port=2181

 when i start the collector and web , i see logs printing
![dasd](https://user-images.githubusercontent.com/15863992/41350112-9f57ced8-6f44-11e8-94d4-7cc3250f77e2.jpg)

did i miss modify any args?

**Comment by RoySRose** [comment]
Hello, @Rnic 
Just looking at the log, it looks like the connection has been refused from the embedded zookeeper in hbase.
Have you noticed, there are two hbase.properties. one for Pinpoint-Collector and one for the Pinpoint-Web. If you have modified both of them, please let me know which has produced those logs that you've posted, the Collector? Web?.

**Comment by Rnic** [comment]
hi,@RoySRose   thank u for your information.
 i had changed two hbase.properties  files,  the picture is from pinpoint-Collector's hbase.properties.
the log always print "connection refused",did't see any another things.
by the way ,  i see the log from pinpoint-web ,it seems like the same question.
you mentioned the embedded zookeeper ,did i need to change anything about the embedded zookeeper?

**Comment by RoySRose** [comment]
hi, @Rnic 
If you had changed two properties files from Collector and the Web. I think that is all you need to do.
Even if you connect to the embedded zookeeper. you don't really need to change anything.

I've mentioned the embedded zookeeper, because I see the word 'zookeeper' in your log file. Since the connection has been refused from Pinpoint-Web to the Hbase. I think you should start from there. Maybe firewall? or anything else?

**Comment by Rnic** [comment]
@RoySRose  thank u for ur help again, i checked the firewall they are closed, and i will try to figure it out
