### ISSUE TITLE
No data shown on web UI 

### ISSUE THREAD

**Issue by beepeng86** [naver/pinpoint#4456]
**What version of pinpoint are you using?**
1.6.2

**Describe your problem**
PinPoint seems to started correctly but no data shown on UI 
![image](https://user-images.githubusercontent.com/18106355/43695887-ebe95a5c-996d-11e8-99dd-8277c034c2fd.png)

**What have you done?**
Steps you have taken to trigger the problem, for example:
1. Follow setup guide to deploy pinpoint web, pinpoint collector, and pinpoint agent, get application started fine. But, no data found on Web UI. Can only see 
![image](https://user-images.githubusercontent.com/18106355/43696083-ded40262-996e-11e8-81d3-83eecde3ed9a.png)
2. Followed https://github.com/naver/pinpoint/issues/2015 but there is no concrete suggestion that actually solve the probem

**Logs**
[001-pinpoint.log](https://github.com/naver/pinpoint/files/2261119/001-pinpoint.log)

**Comment by RoySRose** [comment]
Hello, @beepeng86 

If I look at the second screenshot. It looks like data is flowing correctly since numbers appear on the charts(Heap Usage, PerGen Usage, etc).

 - Were there any transactions created by your application(application that is monitored)
 - Is your application uses any of the [supported modules?](https://naver.github.io/pinpoint/index.html#supported-modules-last-updated-20180401)

**Comment by beepeng86** [comment]
Hi @RoySRose,

1. Yes positive. I've tried quite a few times to wait if it is just some kind of delay between data being collected and data show on web UI. I've also set profiler.sampling.rate=1 in pinpoint.config. 
2. Jboss AS 7, Oracle, redis 

Thanks.

**Comment by RoySRose** [comment]
@beepeng86 
I'm not sure if this will help. But [take a look](https://github.com/naver/pinpoint/tree/master/plugins/jboss)

**Comment by beepeng86** [comment]
Hi @RoySRose, can you please help with this issue? should I try and make it work with version 1.7.3?

**Comment by RoySRose** [comment]
Hello, @beepeng86 

As of the second screenshot. It looks like data is flowing correctly since the numbers appear on the charts(Heap Usage, PerGen Usage, etc).

- Have you looked at the [JBOSS configuration]((https://github.com/naver/pinpoint/tree/master/plugins/jboss)) that I've linked 2days ago?
- is JBOSS AS 7 under JBOSS EAP 6 as shown in [supported modules]([supported modules?](https://naver.github.io/pinpoint/index.html#supported-modules-last-updated-20180401)), I don't have much knowledge in JBOSS
- I've aksed the version of Pinpoint that you are using, just out of curiousity. But Pinpoint-Agent (1.7.X) supports Java 6 ~ 8. from Pinpoint-Agent1.8 starts to supports Java 9. If you don't have any obstacles I recommend you to install hight version.

**Comment by RoySRose** [comment]
Hello, @beepeng86 

Take a look at #2353.
I believe this can be the case since there is 'Not adding JBoss transformers' log in your log file.
Let me know the results :)

**Comment by beepeng86** [comment]
Hi @RoySRose,

Thanks.. I will try it out n revert.

**Comment by beepeng86** [comment]
HI @RoySRose, 
I can now see data on web UI. 
Thanks a lot for your help.
