### ISSUE TITLE
one trace through rabbitmq but split two trace

### ISSUE THREAD

**Issue by zfaster** [naver/pinpoint#4463]
I send one request through rabbitmq but why the request split，pinpoint can not trace the whole trace from rabbitmq？
![image](https://user-images.githubusercontent.com/8341790/43705987-b2399730-9996-11e8-9099-21a28d90ed6c.png)
![image](https://user-images.githubusercontent.com/8341790/43706023-cab8c2fe-9996-11e8-8028-7611c27597c3.png)
![image](https://user-images.githubusercontent.com/8341790/43706058-e0e60064-9996-11e8-9734-8ca0875c02e3.png)

this is my consumer message code
![image](https://user-images.githubusercontent.com/8341790/43706177-3be650a4-9997-11e8-8429-9abf96ce8df2.png)
this is my send message code
![image](https://user-images.githubusercontent.com/8341790/43706193-49292caa-9997-11e8-9d29-38b981a50851.png)

how can I make this trace to a complete trace？

**Comment by Xylus** [comment]
Hi @zfaster 
Please take a look at https://github.com/naver/pinpoint/tree/master/plugins/rabbitmq#tracing-custom-consumers

**Comment by zfaster** [comment]
@Xylus  thank you reply
I try to do but fail
I creat new class 
![image](https://user-images.githubusercontent.com/8341790/43710877-84b55512-99a3-11e8-9699-9d20907c7687.png)
and use it
![image](https://user-images.githubusercontent.com/8341790/43710938-bdf690f2-99a3-11e8-8d48-6bcd4dbeb78c.png)

agent change pinpoint.config
profiler.rabbitmq.client.consumer.classes=com.navercorp.pinpoint.testapp.controller.HelloConsumer

restart agent
I found the config has success, but the **doInTransform** method can not be invoke ,and the trace result also split two
![image](https://user-images.githubusercontent.com/8341790/43710992-e8b4fb4e-99a3-11e8-8656-37099b904946.png)

so,where I config error?

**Comment by Xylus** [comment]
@zfaster The `doInTransform()` is invoked when the custom consumer is actually loaded.
Since `doInTransform()` is not invoked, then your **HelloConsumer** seems to never have been loaded.

Please make sure you have configured `profiler.rabbitmq.client.consumer.classes` properly (ie. the fully qualified class name of **HelloConsumer**) and that you have rebuilt your test app.

**Comment by zfaster** [comment]
@Xylus 
![image](https://user-images.githubusercontent.com/8341790/43713993-14b53c18-99ae-11e8-8662-5000cb1e9513.png)
![image](https://user-images.githubusercontent.com/8341790/43715582-8397f4c2-99b3-11e8-9871-b114505bbf88.png)

**I config correct, and rebuild and restart server,but no use;**
and if change the code to super.handleDelivery(consumerTag,envelope,properties,body); it also will split the request; when change to super the request has inercept by ConsumerHandleDeliveryInterceptor
![image](https://user-images.githubusercontent.com/8341790/43715698-ec949520-99b3-11e8-85f8-b3458644c103.png)

**Comment by zfaster** [comment]
@Xylus 
I found the RabbitMQConsumerDispatchInterceptor can not get trace info
![image](https://user-images.githubusercontent.com/8341790/43750669-0d78c978-9a2c-11e8-9ce6-b4d164285732.png)

when send message the ChannelBasicPublishInterceptor has set header info ,why can not get?
![image](https://user-images.githubusercontent.com/8341790/43750753-6bb72034-9a2c-11e8-84b9-0b76ee7b62d0.png)

**Comment by Xylus** [comment]
@zfaster 
You've looked at the right place :+1: 
I've managed to recreate your issue, and there are 2 things going on.

1. A `null` header is passed when sending message
The RabbitMQ plugin adds pinpoint-specific headers to `AMQP.BasicProperties` to propagate trace over process boundaries.
However, if properties is not specified (`null`) as in your example, `sendChannel.basicPublish("", QUEUE_NAME, null, message.getBytes("UTF-8"))` there is no properties in which to add pinpoint-specific headers.
The RabbitMQ plugin will have to modified to support these cases as passing null as properties is allowed, but this will take some time and will probably be released in 1.8.1.
In the mean time, you could change your send code to `sendChannel.basicPublish("", QUEUE_NAME, MessageProperties.MINIMAL_BASIC, message.getBytes("UTF-8"))`, which will allow the interceptor to add pinpoint-specific headers.

2. `HelloConsumer` is under `com.navercorp.pinpoint` package
When pinpoint agent adds class file transformers to inject trace code, it skips any classes under `com.navercorp.pinpoint` package. This is done so that we do not modify any internal classes.
Since your `HelloConsumer` is under `com.navercorp.pinpoint.testapp.controller`, it will be skipped and won't be traced.
Refactoring out `HelloConsumer` to a different package that is not under `com.navercorp.pinpoint` will have it working correctly.

So with the issues above in mind, modifying your sender code to use `sendChannel.basicPublish("", QUEUE_NAME, MessageProperties.MINIMAL_BASIC, message.getBytes("UTF-8"))`, and moving your `HelloConsumer` class to a different package will fix your issue.

**Comment by zfaster** [comment]
@Xylus 
It work! thank you very much!
