### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by mastiffs1990** [naver/pinpoint#4575]
Hi,
I need to install the complete pack of Pinpoint APM.
I'd like to know if it's better to install HBase and Collector on multiple servers or on a single server? Considering the impact that HBase could have.
What system requirements (CPU, RAM etc...) need Pinpoint-release 1.7 ?
Greetings.

**Comment by RoySRose** [comment]
Hello, @mastiffs1990 

Well, it totally depends on the status of your service and how much resources you can provide to operate Pinpoint.
But, Since Pinpoint's main goal is to monitor large-scale distributed system, it's designed to fit running on multiple servers.

We don't have any minimum hardware requirements standards. 
Maybe this can help you #2314
