### ISSUE TITLE
How to display the topology of distributed system 

### ISSUE THREAD

**Issue by ryshhxq** [naver/pinpoint#4685]
pinpoint version is 1.8.0-RC1
![img1](https://user-images.githubusercontent.com/40416536/46254805-07ecc800-c4d0-11e8-96e3-291674578e15.jpg)
![img2](https://user-images.githubusercontent.com/40416536/46254806-091df500-c4d0-11e8-9837-b0697b105172.jpg)

How to display the effect of  img2 in img1?
※user→tomcat→weblogic's logic is Implemented in source code!!
How to make weblogic's image display in img1?

**Comment by RoySRose** [comment]
Hello, @ryshhxq 

I can see that img2 shows the *server map* of a transaction
and img1 shows the *server map* of the whole system.

If img1 and img2 represents the same system, the *server map* of img2 will show on the first page(img1) automatically.
I assume that the reason that it's not showing on img1 is because the `Real time` only displays
the server map of recent 5 mins.

**Comment by Xylus** [comment]
This looks very similar to #4673
