### ISSUE TITLE
How to implant pinpoint agent into docker container

### ISSUE THREAD

**Issue by huangchaobing** [naver/pinpoint#4892]
My dockerfile configuration file as follow:
FROM public-docker-virtual.artnj.zte.com.cn/java:openjdk-8u111-jre-alpine
MAINTAINER Devops
COPY @project.build.finalName@.jar /app.jar
COPY pinpoint.config /pinpoint.config
COPY pinpoint-bootstrap-1.8.0.jar /pinpoint-bootstrap-1.8.0.jar
RUN touch /app.jar && 
touch /pinpoint.config && 
touch /pinpoint-bootstrap-1.8.0.jar

CMD java -javaagent:/pinpoint-bootstrap-1.8.0.jar -Dspring.profiles.active=docker -Dpinpoint.agentId=pinpoint-client-alert -Dpinpoint.applicationName=pinpoint-client-alert -jar /app.jar

  when I start this micro-container with docker-compose,it generates  error info:

 Error opening zip file or JAR manifest missing:/pinpoint-bootstrap-1.8.0.jar
 Error occurred during initialization of VM
 agent library failed to init: instrument

How to solve this problem,thanks?

**Comment by RoySRose** [comment]
Hello, @huangchaobing 

As I've said earlier.  The error message
`Error opening zip file or JAR manifest missing:/pinpoint-bootstrap-1.8.0.jar`
means that jar file is not there or misplaced.
I'd check the location of the file. 

Trying to compare with docker-compose in our [pinpoint-docker repository](https://github.com/naver/pinpoint-docker) may help you find the problem.

I can't find the exact problem for you since there are several enviroment difference such as docker versions, compose version, etc.
Furthermore, this issue is related to docker settings.
