### ISSUE TITLE
Central pinpoint for multiple sites 

### ISSUE THREAD

**Issue by pbusquemdf** [naver/pinpoint#4961]
Is it possible to centralize Pinpoint so that it can be used by various, independent sites?

According to the docs, the way to labels applications added to Pinpoint is the following:

applicationName: Reference to a group of program sharing the same functionality. Ex: Front-end, search engine, security agents, etc. Each appears as a distinct node in the graph.
agentId: A distinct name for an application. They are all grouped into the same node in the graph.

If we have multiple distinct sites, is there a way to have them all in clustered set of Pinpoint, Collector  and Cassandra, so that we have a centralized APM instance, or do we have to set up a trio of Cassandra,  Pinpoint, Collector for every site we plan to integrate Pinpoint into?

Or is Cassandra the only sharable component using namespace?

This is particular important license wise because of this issue: https://github.com/naver/pinpoint/issues/1308

If we have multiple site and we need multiple instance of Pinpoint UI, and that each need a separate licence for each website, this would skyrocket the cost for an OSS.

**Comment by Xylus** [comment]
Hi @pbusquemdf 
Yes, this is possible, but is not supported out of the box, so you will have to decide and implement how you would segregate data by clients.

Regarding the license, we are in the process of revamping the UI so that the license is no longer required. We expect this to be live in a few months.
Thanks.
