### ISSUE TITLE
Can pinpoint intercept Java's Socket invocations to other systems?

### ISSUE THREAD

**Issue by fengnex** [naver/pinpoint#5126]
- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

 We have a java web application which communicates with other C/C++ systems through java Socket. But there are no any those C/C++ applications symbols in the corresponding topology.

I wonder how to detect these applications and collection their invocation records.

**Comment by Xylus** [comment]
Hi @fengnex 
Pinpoint does not trace C/C++ applications (yet hopefully).
If you're calling your C/C++ application using one of the supported libraries (such as Apache HTTP client if you're making a HTTP call, etc) then the C/C++ node should show up as an unknown cloud.
Otherwise the RPC invocation cannot be traced currently.

**Comment by fengnex** [comment]
@Xylus When we use java's Socket class to communicate a C/C++ application, pinpoint is expectecd to be able to detect and intecept the communication and corresponding applications.

Do you mean it is not possible currently even for Java's Socket? Are there any plans in the future if so?
Thanks.

**Comment by Xylus** [comment]
For plain old socket using your own custom protocol, no.
We need to hook interceptors and add trace data in order to record/propagate trace, and we can't do this if you're rolling your own protocol as we have no idea where to intercept (for recording) and how to serialize trace data (for propagation).

I don't think we have any plans to trace native socket calls.
What I would suggest is to make a simple plugin around the method that you want to trace and record whatever information you need.
