### ISSUE TITLE
When I use weblogic with pinpoint-1.8.0, but there is no topo and dotList Graph, and the  ServiceType show “UNDEFINED”

### ISSUE THREAD

**Issue by zhoukaidian** [naver/pinpoint#5155]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

**Comment by zhoukaidian** [comment]
Only JVM info in the inspector

**Comment by zhoukaidian** [comment]
and the network(9994, 9995, 9996) is ok

**Comment by Xylus** [comment]
Hi @zhoukaidian 
Please check your agent log (DEBUG level) to see if anything's wrong.
Also, take a look at the [readme](https://github.com/naver/pinpoint/tree/master/plugins/weblogic).

**Comment by zhoukaidian** [comment]
Hi @Xylus 
I tried to do that,but it still didn't work and no abnormalities in agent log.

**Comment by zhoukaidian** [comment]
Hi @Xylus 
I tried to do that,but it still didn't work and no wrong in agent log.
And http response shows 'serviceTypeCode:-1' in nodeDataArray.
Is it related to the weblogic version?

**Comment by Xylus** [comment]
The http response is showing `serviceTypeCode:-1` since the service type is UNDEFINED.

It's not possible to figure out what's wrong since you haven't really provided any information about your issue.
[Here](https://github.com/naver/pinpoint/issues/new?template=troubleshooting.md) is the troubleshooting template. Please edit this issue or create a new one using it.

**Comment by Xylus** [comment]
moved to #5167
