### ISSUE TITLE
a mongo plugin question

### ISSUE THREAD

**Issue by tonfay** [naver/pinpoint#5282]
Now I use the latest master code for packaging, and there is no support for mongo, may I ask what configuration should I change?

agent-config
###########################################################
# MONGODB
###########################################################
profiler.mongo=true
profiler.mongo.collectjson=true
profiler.mongo.tracebsonbindvalue=true

**Comment by RoySRose** [comment]
Hello, @tonfay 

There isn't anything else to configure.
How do you access mongodb? by mongodb-java-driver?

**Comment by tonfay** [comment]
by spring boot - mongo,Support?
@RoySRose

**Comment by tonfay** [comment]
spring-boot-starter-data-mongodb
"mongodb-driver"
not "mongodb-java-driver"
@RoySRose 

Support? tks!

**Comment by tonfay** [comment]
After the test,
pinpoint 1.8.1 Spring Boot MongoTemplate is not supported.
Is this the case?
@RoySRose @koo-taejin

**Comment by RoySRose** [comment]
Hello, @tonfay 

Please check the announcements on our [homepage](https://naver.github.io/pinpoint/1.8.1/main.html#pinpoint-plugin)
for bugs of the plug-in. Suggest you upgrade the version of Pinpoint to v1.8.2.

Spring Boot is supported through Spring-Boot-Plugin
and 
MongoDB-Plugin supports 
 - mongodb-java-driver
 - spring-data-mongodb

I didn't really test 
 - spring-boot-starter-data-mongodb

But, since it is just a wrapper of others.
![image](https://user-images.githubusercontent.com/20402016/53537825-8cf70e80-3b4e-11e9-81c4-78eb0879ae1c.png)

I think It has high probability of support.

Please upgrade version of Pinpoint, and It would be great if you share us the results :)
I'll be waiting for your reply.

**Comment by tonfay** [comment]
hello @RoySRose 
The version I am using now is the "master" version, which should be "1.9.0".
1.Need to downgrade to 1.8.2?
2.Want to test "spring-boot-starter-data-mongodb",I didn't use it effectively
3.
but,The following code is available
MongoClient client = new MongoClient("127.0.0.1",27017);
MongoDatabase db = client.getDatabase("test");
MongoCollection<Document> collection = db.getCollection("test_coll");
long a = collection.count();

Hope to reply!

**Comment by RoySRose** [comment]
> After the test,
> pinpoint 1.8.1 Spring Boot MongoTemplate is not supported.
> Is this the case?

I thought you were using 1.8.1. 
If you are using the current master version no downgrade is needed. 

If below is the code from your application. MongoDB should be detected, since 
MongoClient, getDatabase(), getCollection() are all instrumented.

```java
MongoClient client = new MongoClient("127.0.0.1",27017);
MongoDatabase db = client.getDatabase("test");
MongoCollection collection = db.getCollection("test_coll");
long a = collection.count();
```

I need some log to verify the problem.
A simple sample app would be a fastest way to get to the conclusion

**Comment by tonfay** [comment]
hello @RoySRose 
That's  right.

```
MongoClient client = new MongoClient("127.0.0.1",27017);
MongoDatabase db = client.getDatabase("test");
MongoCollection collection = db.getCollection("test_coll");
long a = collection.count();
```

The above no problem。
but  `spring-boot-starter-data-mongodb`  is failure。
What logs do you need that I can provide to you

**Comment by RoySRose** [comment]
@tonfay 

I'd like to see debug log of Pinpoint-Collector and Pinpoint-Agent.

By the way. Do you at least see the (spring booted) application?

You should at least see one node(spring boot app). 
If you don't see anything you need to set the starting point for spring-boot app

**Comment by tonfay** [comment]
In the current version, the following classes are intercepted
3.0.0 ~ 3.6.4
com.mongodb.Mongo
com.mongodb.MongoClient
com.mongodb.MongoDatabaseImpl
com.mongodb.MongoCollectionImpl
com.mongodb.client.model.Filters
com.mongodb.client.model.Updates
com.mongodb.client.model.Sorts

3.7.0+
...

but,
`spring-data-mongodb` Does not use `pinpoint` intercepted by the class list。
If you can support `com.mongodb.DBCollection`  That might be fine。


ps：
`spring-data-mongodb` 
`org.springframework.data.mongodb.core.MongoTemplate`

**Comment by tonfay** [comment]
![image](https://user-images.githubusercontent.com/19604131/53549225-a1e39a00-3b6e-11e9-8bc6-579780f3e40b.png)
![image](https://user-images.githubusercontent.com/19604131/53549286-cdff1b00-3b6e-11e9-9af2-a36501c5433e.png)

**Comment by RoySRose** [comment]
@tonfay 

`org.springframework.data.mongodb.core.MongoTemplate`
wraps 
`mongodb-java-driver`

![image](https://user-images.githubusercontent.com/20402016/53549520-b710f680-3b77-11e9-95bd-c0162b0b698a.png)

I've also run the test with a sample app

![image](https://user-images.githubusercontent.com/20402016/53549582-e0ca1d80-3b77-11e9-9fde-054d26e06c41.png)

why do you get `Collection` from mongoTemplate?
Try getting count by temp.count(~~);

Correct me if I'm wrong. When you use mongoTemplate, shouldn't it be used such
```java
mongoTemplate.insert(user, Collection_name)
```
not
```java
mongoTemplate.getCollection("Collection_name").insertOne(Bson ~)
```
If you CRUD with the Collection returned from mongoTemplate.getCollection().
isn't `spring-data-mongodb` not needed in the first place?
Why use mongoTemplate, if you are going using by retrieving Collection from mongoTemplate.

**Comment by tonfay** [comment]
@RoySRose 
First of all, thank you for your continuous reply.

There's a lot going on with mongoTemplate。

You have this way, can pinpoint web show the call stack?
Can you take a picture?

**Comment by RoySRose** [comment]
@tonfay 

Of course, 
server map
![image](https://user-images.githubusercontent.com/20402016/53551794-67352e00-3b7d-11e9-9863-69a01641090a.png)

call stack
![image](https://user-images.githubusercontent.com/20402016/53551886-9b105380-3b7d-11e9-991d-58d20c854f9a.png)

controller
![image](https://user-images.githubusercontent.com/20402016/53551922-a9f70600-3b7d-11e9-8619-b2129e017810.png)

skipping service since there is nothing significant

Dao - mongoTemplate
![image](https://user-images.githubusercontent.com/20402016/53552083-ee82a180-3b7d-11e9-8619-e9d338adf912.png)

If you return Collection from the template and use it. I think, it won't be traced. Because I didn't implement to sustain the `Collection` when retrieved from the template.
BUT, I think mongoTemplate.getCollection() method's intend was for something else, not to get collection and use it from there. (Correct me if I'm wrong)

**Comment by RoySRose** [comment]
@tonfay 

And If I'm wrong about the intent of mongoTemplate.getCollection() method.
Maybe you can help me add the function by making a PR on it. It won't take much time.

**Comment by tonfay** [comment]
I tried to increase it `mongoTemplate.getCollection()`
But it hasn't worked yet. It's being tried...


In addition,
I'm in the same situation as your code, and I'm not showing the call stack here.
mongodb-driver-3.4.3.jar ,
I'll try the same version as yours,3.8.2

**Comment by tonfay** [comment]
@RoySRose 
```
private void addSessionTransformer3_0_000_X() {
        transformTemplate.transform("com.mongodb.DBCollection", SessionTransform3_0_000_X.class);
    }

    
    public static class SessionTransform3_0_000_X implements TransformCallback {
        @Override
        public byte[] doInTransform(Instrumentor instrumentor, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws InstrumentException {
            final InstrumentClass target = instrumentor.getInstrumentClass(loader, className, classfileBuffer);

            if (!target.isInterceptable()) {
                return null;
            }

            target.addField(DatabaseInfoAccessor.class);

            MongoConfig config = new MongoConfig(instrumentor.getProfilerConfig());

            for (InstrumentMethod method : target.getDeclaredMethods(MethodFilters.chain(MethodFilters.modifier(Modifier.PUBLIC), MethodFilters.name(getMethodlistR3_0_x())))) {
                method.addScopedInterceptor(MongoRSessionInterceptor.class, va(config.isCollectJson(), config.istraceBsonBindValue()), MONGO_SCOPE, ExecutionPolicy.BOUNDARY);
            }

            for (InstrumentMethod method : target.getDeclaredMethods(MethodFilters.chain(MethodFilters.modifier(Modifier.PUBLIC), MethodFilters.name(getMethodlistCUD3_0_x())))) {
                method.addScopedInterceptor(MongoCUDSessionInterceptor.class, va(config.isCollectJson(), config.istraceBsonBindValue()), MONGO_SCOPE, ExecutionPolicy.BOUNDARY);
            }

            return target.toBytecode();
        }
    }

MongoPlugin.setup(){
...
addSessionTransformer3_0_000_X();
...
}
```

If I add it like this, is there a problem?

**Comment by RoySRose** [comment]
mongodb-java-driver's version isn't really the issue. I've checked it works in versions 3.0+ and above.

You should check. How
MongoClient, MongoDatabase, and MongoCollection
are created in the first place. If they are derived from mongodb-java-driver, It will be traced.

and about modifying plug-in. You need to implement getting MongoCollection part. Find where `MongoDriverGetCollectionInterceptor` is called.

**Comment by tonfay** [comment]
hi @RoySRose 
To save time, can you lower the version of spring-boot?
And then let's run it,Because I now suspect that it is my use of the version of the problem, if you use the same version as me, you there is normal, then I may consider my local problems
Very simple
Just change the following

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.12.RELEASE</version>
</parent>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-mongodb</artifactId>
	<version>1.5.12.RELEASE</version>
</dependency>
```
tks!

**Comment by tonfay** [comment]
I have been testing
```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.12.RELEASE</version>
</parent>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-mongodb</artifactId>
	<version>1.5.12.RELEASE</version>
</dependency>
```
pinpoint-web don't support

**Comment by rubyvirus** [comment]
@RoySRose @tonfay can you share your source code for mongo monitoring test

**Comment by RoySRose** [comment]
Hello, @rubyvirus 

I think you can just make a simple CRUD with spring and it will work.
Unfortunately, I don't have any test code ready to be open.

**Comment by yjqg6666** [comment]
For spring-boot-starter-data-mongodb:1.5.x it would not working, since DBCollection is used even though mongodb-driver 3.x is depended upon. DBCollection instrumentation is needed. [The patch](https://github.com/naver/pinpoint/issues/5282#issuecomment-468188579) @tonfay provided is needed and confirmed. I make a PR #7077 to support this. @RoySRose any thought?
