### ISSUE TITLE
Can i setup pinpoint-agent on gemfire cache server ?

### ISSUE THREAD

**Issue by ManjunathSwamy** [naver/pinpoint#5285]
I am trying to configure pinpoint-agent on gemfire cache server and also on a spring boot application that connects to gemfire. 
I am able to see both apps getting registered on pinpoint web. But no data when i perform put/get on to gemfire cache from springboot. 
Can you please help me ?

**Comment by Xylus** [comment]
Hi @ManjunathSwamy 
It seems like it's because pinpoint doesn't support gemfire, so no trace is generated for put/get on the client side, and the gemfire cache side.
I don't think we can get support for gemfire in any time soon as none of us are very familiar with it.

If you'd like to make a plugin for gemfire and throw us a PR, it would be great.
Let me know if you'd like to work on a plugin so I can point you in the right direction and help out.
Thanks

**Comment by manjunathsv1947** [comment]
Thanks @Xylus 
As of now we are doing a POC (Proof Of Concept) on all our applications that pinpoint can support, Without custom changes! Plugin development is going to be future task.

**Comment by Xylus** [comment]
Awesome, let me know if you have more questions.
