### ISSUE TITLE
Error information cannot be collected if global exceptions are handled with @RestControllerAdvice and @ExceptionHandler

### ISSUE THREAD

**Issue by yu412346928** [naver/pinpoint#5299]
pinpoint version:1.6.2
springboot version:2.0.8
embedded tomcat version:8

problem description:
Error information cannot be collected if global exceptions are handled with @RestControllerAdvice and @ExceptionHandler

**Comment by Xylus** [comment]
Hi @yu412346928 
Where did the exception occur? Does the exception show up in the call stack at all?
You might also want to check `profiler.spring.beans.mark.error` option in *pinpoint.config* since if disabled, will not record exceptions thrown by spring beans. This combined with the fact that exceptions are handled globally (so not propagated to Tomcat level), might cause what you're seeing.

**Comment by yu412346928** [comment]
Hi @Xylus 
![1](https://user-images.githubusercontent.com/8243819/53938382-0fea0d00-40eb-11e9-91f7-9b03a357d1b2.png)

![2](https://user-images.githubusercontent.com/8243819/53938509-7707c180-40eb-11e9-86a6-e8d768a93772.png)

**Comment by Xylus** [comment]
Thanks, have you checked `profiler.spring.beans.mark.error` in *pinpoint.config*?

**Comment by yu412346928** [comment]
@Xylus  thanks.

profiler.spring.beans.mark.error=true

Succeed

**Comment by Xylus** [comment]
yay!
