### ISSUE TITLE
what is the Gap time

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#5398]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Hi, i know the gap time's definition，but i cannot understand the gap time of the application。As shown in the chart below.

![image](https://user-images.githubusercontent.com/26397343/54904075-67c0aa80-4f18-11e9-96c1-a3615335e382.png)

I guess, is it caused by the httpurlconnection ?

thanks!

**Comment by emeroad** [comment]
Pinpoint only shows the current status. You have to find the problem yourself. 

This could be a network problem such as l4, or it could be WebServer or WAS. 
Check all layers related to network communication.

**Comment by emeroad** [comment]
https://www.slideshare.net/deview/164-pinpoint/109

Typically occurring in the following situations:
## TCP connect problem
 - tcp connect is delayed
 - socket option: connectTimeout, socket backlog
 - webserver: apache, nginx
 - network switch : loadbalancer (l4)
 - client attribute: httpclient retry policy

**Comment by fionaliupw** [comment]
@Xylus thank you, I already know what the reason is. It caused by webserver.
About gap time, I hava another question. If the gap time is a negative value，what does it mean?

**Comment by Xylus** [comment]
Hi @fionaliupw 
I think you meant @emeroad :)

Negative gap time means the child method started before the parent's (parent-child in the context of call stack), or might be a bug.
It could mean that the child trace really did start before the parent, such as if the child method started and is blocking on something waiting for a value from the parent.
Or it could be due to clock skew.
Or it could be due to a bug in the plugin.
Or it could be due to something else that I'm missing.

If you think it might be due to a bug, please do provide us with some detail so we can take a look at it.
Thanks.
