### ISSUE TITLE
tspan's ExceptionInfo is null.

### ISSUE THREAD

**Issue by shaocongcong** [naver/pinpoint#5495]
I accessing the HTTP service make an error. in tspan, tspan's Err is 1 but  tspan's  ExceptionInfo is null , this err msg is in eventlist.  
Is there an error in the event list， tspan’s err is 1?

**Comment by Xylus** [comment]
Hi @shaocongcong
I'm not sure if I understood your question, but tspan's ExceptionInfo could be null if exception's message is null.
Also, if tspan's err is 1, then one of the interceptors would have recorded an exception.

**Comment by shaocongcong** [comment]
I did an experiment here, requesting a wrong network address in a tomcat service, and printing the tspan information found the following problem:
   1. The err field of tspan is 1, but the ExceptionInfo field is empty and the error message is in the eventlist.
   2. The exception to the access address appears twice in the eventlist.

**Comment by shaocongcong** [comment]
I used the version v1.8.0 and recently found a problem.
The reported stat data in TAgentStatBatch.Gc.GcDetailed.JvmPoolPermGenUsed is -1.

**Comment by Xylus** [comment]
Hi @shaocongcong 
Span's error field will be set to 1 if any of it's span events records an exception (via `SpanEventRecorder.recordException(Throwable)` and the span's exception info field will be empty if the error was set this way.
Since you have errors in the span event list, I think this is what happened.

The exception may also appear more than once if the exception is propagated up the call stack with more than 1 method traced by the agent.
(All plugin interceptors encountered during the propagation will record the exception)

Regarding your second issue, if you're running your application on Java 8, it will be -1 as permgen is removed. If you're not running on Java 8, please check and let me know if other detailed gc metrics are being collected.

**Comment by shaocongcong** [comment]
Hi @Xylus 
Thank you for your reply. I have two more questions to ask for help.  
1. Which field does Permgen take in JDK version 1.8 
2. When testing dubbo service, I found that sometimes the KeyTime in TSpanChunk is 0

**Comment by Xylus** [comment]
Hi @shaocongcong 
Happy to help.
1. You might want to check metaspace for Java 8
2. Can't really figure out what's going on without more detail/a way to replicate it. But you might want to check the span events in the span chunk as they key time assumes the start time of the first span event (ordered by sequence) in the span chunk.

**Comment by emeroad** [comment]
2. KeyTime in TSpanChunk is currently not used
KeyTime is used in SpanV2 compression spec for grpc
https://github.com/naver/pinpoint/blob/6bb99cab7d48196f41fc40418927e3470ad606d2/profiler/src/main/java/com/navercorp/pinpoint/profiler/context/compress/SpanProcessorProtoV2.java#L68

**Comment by shaocongcong** [comment]
@Xylus @emeroad 
Thank you for your answers!
