### ISSUE TITLE
why should set profiler.jdbc.postgresql.setautocommit=false

### ISSUE THREAD

**Issue by bryanYao** [naver/pinpoint#5519]
i use pinpoint with spring cloud, and my database is postgresql;
I'm a little confused about agent configuration that in pinpoint-real-env-lowoverhead-sample.config it suggest that

**profiler.jdbc.postgresql.setautocommit=false
profiler.jdbc.postgresql.commit=false
profiler.jdbc.postgresql.rollback=false**

why should set false in online environment;

can any one tell me the reason?  many thanks!

**Comment by Xylus** [comment]
Hi @bryanYao 
setautocommit, commit, and rollbacks are usually automatically handled via transaction.
Since *pinpoint-real-env-lowoverhead-sample.config* aims to be light weight, the sample configuration turns tracing these methods off. (you can always leave them on if you'd like)

Note that disabling these options **does not** affect commits and rollbacks of your application. It merely does not **trace** these methods so they do not show up in Pinpoint Web UI's call stack.
