### ISSUE TITLE
Unable to collect calls of Weblogic 10.3.6

### ISSUE THREAD

**Issue by chengwei999** [naver/pinpoint#5844]
[ √] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I'm trying pinpoint version 1.8.1, agent deployed in Weblogic version 10.3.6. At present, it is found that only SQL statements executed by Weblogic through JDBC can be collected, and calls between applications and other systems can not be collected. I wonder if Weblogic version 10.3.6 is not currently supported.

**Comment by Xylus** [comment]
Hi @chengwei999 
So you mean SQL statements and jdbc calls are showing up in the call stack, right?
I don't think the Weblogic plugin is the problem here then as you have SQLs and jdbc calls traced. 
(The Weblogic plugin must have started a trace in order for the jdbc calls to be traced as well)

How are you calling other applications? Is there a thread switch before these calls are made?

**Comment by chengwei999** [comment]
I confirm that threads are executed synchronously, without switching。Is that the reason for calling other applications through web service，and the class is org.apache.axis.client.AxisClient

**Comment by Xylus** [comment]
Ah okay, I think your external calls aren't getting traced because Pinpoint doesn't support Axis client.
It would be great if you could make a plugin for Axis and throw us a PR!

**Comment by chengwei999** [comment]
https://imgchr.com/i/e7CM2F from pinpoint
https://imgchr.com/i/e7CBKH from riverbed

**Comment by chengwei999** [comment]
Thank you, but I'm an operations engineer and can't write JAVA code. I hope you can support Axis soon
