### ISSUE TITLE
How do I randomize agentID in cloud scaling?

### ISSUE THREAD

**Issue by ObiJonKenobi89** [naver/pinpoint#5902]
#### Prerequisites
- [x ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Hi team,

I'm looking to utilize Pinpoint APM on our GCP platform which uses autoscaling instance groups. 

When setting setenv.sh with the argument CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=$((1000 + RANDOM % 9999)) and then stress testing the instance group to autoscale, it's not generating a random four digit number ID or updating the agent list. 

Manually setting the agent IDs will be impossible when instances in the instance group are created from a single image. How do I ensure that a random four digit agent ID is generated? And, additionally, how do I remove stale entries from the agent list or in inspector view?

**Comment by Xylus** [comment]
Hi @ObiJonKenobi89 
Not sure why it's generating the same value, but maybe try initializing them with a random seed?

Or instead of using a 4 digit random with a possibility of collision, an option would be to use an environment variable provided by GCP instance with an unique value if there are any. 
(truncated to 24 characters if they're longer than this)

If there's an instance specific uuid you can access, that would be best, if not you could maybe generate your own uuid?
Either way, you'll want to base64_url encode them to bring them down to 22 characters,
The following is an example of how to create an uuid and base64_url encoding them if you have python available.
Please feel free to play around with it to fit your needs.
```
PINPOINT_AGENT_ID=$(uuidgen)
PINPOINT_AGENT_ID=`python -c "import base64; import uuid; id = uuid.UUID('${PINPOINT_AGENT_ID}'); shortened = base64.urlsafe_b64encode(id.bytes); print shortened.replace('=', '');"`

CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=$PINPOINT_AGENT_ID"
```

**Comment by ObiJonKenobi89** [comment]
Thank you very much for the swift response! 

I'm not going to lie -- I don't really come from a developer background, so using a variable generated / provided by the GCP instance is something I don't know how to do. Currently, it seems like creating a UUID per instance is the most appropriate way forward. 

Thanks again for the response, I'll do some testing on this.

**Comment by Xylus** [comment]
Awesome, let me know if anything doesn't work.
Also, please do share your testing result as it'll be useful for others deploying to cloud instances with similar questions.
Thanks!
