### ISSUE TITLE
Support different storages

### ISSUE THREAD

**Issue by paul-ovchinnikov** [naver/pinpoint#6050]
Consider to support more resource friendly data storage contrast to HBase:
* [ClickHouse](https://clickhouse.yandex/)
* [Apache Cassandra](http://cassandra.apache.org/)

**Comment by RoySRose** [comment]
Pinpoint aims to help people who'd like to monitor MSA efficiently.
There are various logics implemented in Pinpoint to enhance performance to monitor tremendous data.
In the current situation, multiple storage support would require heavy resource and that is what we don't have.
There is no plan to support different storages for now (Nevertheless, the architecture of Pinpoint is prepared for alternative storage)
Even if we set the plans. It would be storages that handle big data rather than the one you've mentioned.
