### ISSUE TITLE
index server map has Incorrect link line

### ISSUE THREAD

**Issue by zifeihan** [naver/pinpoint#6115]
hello ,I use pinpoint 1.8x. the index server map has Incorrect link line about kafka plugin, un expect  zero like line. like this. 
through debug the pinpoint source, i notice com.navercorp.pinpoint.plugin.kafka.interceptor.ConsumerRecordEntryPointInterceptor.TraceFactoryProvider.DefaultTraceFactory#recordRootSpan(com.navercorp.pinpoint.bootstrap.context.SpanRecorder, org.apache.kafka.clients.consumer.ConsumerRecord, java.lang.String, java.lang.String) record span endPoint is kafka bootstrap.servers, i think it should record the real kafka consumer client server address.
![image](https://user-images.githubusercontent.com/16839929/67355966-506b9d80-f58b-11e9-9a53-270b830e538a.png)

**Comment by koo-taejin** [comment]
hi @zifeihan 

The issue is expected to be resolved by the following commit:
https://github.com/naver/pinpoint/commit/63d014c33bb4c04f0e38c4fa8a8efee7c2e3d642

But the above solution is not the perfect solution to what you say.
Because the Kafka is a logical node, it's different from the previous one, and it requires further consideration.

In addition, this commit apply only to the master.
Pinpoint team is preparing for release 1.9.0-RC1 version in November.
It is not expected to change much from the current master's code.
If you can try master branch and the problem is solved, then I recommend you to use 1.9.0 version that will be release.  
 
thanks. :)

**Comment by zifeihan** [comment]
> hi @zifeihan
> 
> The issue is expected to be resolved by the following commit:
> [63d014c](https://github.com/naver/pinpoint/commit/63d014c33bb4c04f0e38c4fa8a8efee7c2e3d642)
> 
> But the above solution is not the perfect solution to what you say.
> Because the Kafka is a logical node, it's different from the previous one, and it requires further consideration.
> 
> In addition, this commit apply only to the master.
> Pinpoint team is preparing for release 1.9.0-RC1 version in November.
> It is not expected to change much from the current master's code.
> If you can try master branch and the problem is solved, then I recommend you to use 1.9.0 version that will be release.
> 
> thanks. :)

ok, thanks. it can be worked well on master branch.
