### ISSUE TITLE
Get Tracing Data from Pinpoint Web

### ISSUE THREAD

**Issue by martinstraesser** [naver/pinpoint#6255]
Hello all,

I instrumented a medium-scale application consisting of microservices with Pinpoint 1.8.4. I want to do further processing of the collected data. I have already extracted the application names (via `applications.pinpoint`) and performance data like average response time (via `getServerMapDataV2.pinpoint`). What I need now are some tracing data for each service. My aim is to build an application topology as shown in the server map. More specifically, I need for each service:
-no. of incoming requests within a time interval and for each request the request type (e.g. GET, POST)
-no. of outgoing requests within a time interval, their types (e.g. GET, POST) and their target service

So, a processed output could be:
In the time interval 0 to 100 service A sent 1 POST request and 2 GET requests to service B.
In the time interval 0 to 100 service B received 2 POST requests and 4 GET requests.

Is there a way, to get these data from Pinpoint Web? Moreover, is there an overview/documentation, which describes all Pinpoint Web endpoints such as `applications.pinpoint`?

Thanks for any help or advices!
Greetings, 
Martin

**Comment by koo-taejin** [comment]
hi @martinstraesser 

The average response time is stored in a separate table, so it can be showed right away. 

However, the service you're talking about needs to bring every request.
Because they are not stored separately. For this reason, only statistics of requests being sampled can be proccessed.

To make this possible, the associated data must be stored to somewhere.

If you do this and contribute to us, it will help us a lot.

thanks :)

**Comment by martinstraesser** [comment]
Hello @koo-taejin 
I think you have these kind of data already stored, I can extract these data from this table in the `transactionView`. 

![TransactionView](https://user-images.githubusercontent.com/26547750/70042130-a38b3400-15be-11ea-89b9-6fbf9772733e.png)

So the question is how to get these data from the table? I think these data might be accessible by using `transactionInfo.pinpoint`. But I can not call this endpoint properly as it requires a parameter named `traceId`, which I dont know where to get this from. Can you give an example call and output of `transactionInfo.pinpoint`? I think this would help me much at the moment.

**Comment by koo-taejin** [comment]
@martinstraesser 

As you said, in the `transactionInfo` method you get everything.
However, it's not refined data, so even HBase can be very hard.

In addition if you want to request `transactionInfo`, you must know the traceId to call that method.
The traceId can be obtained through the `getScatterData` method.
However, It is not a raw data because of in order to reduce size of data.
It will be help that you to see the internal code.

In addition, these methods can change at any time for some reasons.
If you will do this, Please leep this in mind.

thanks :)

**Comment by martinstraesser** [comment]
@koo-taejin 

Thank you for your answer, I'm getting closer to the data I want :) I'm able to access `transactionInfo.pinpoint` now. One last question: Is there a simple way to get all `transactionId`s created within a time interval? Example could be:

Call:
`http://IP:PORT/getAllTransactionIds.pinpoint?from=1&to=2`

Response:
```
{
   "idlist": {
      "1": agent-1^1575622767457^1,
      "2": agent-1^1575622767457^2,
      "3": agent-2^1575622767602^1
    }
}
```

I'm searching for a proper way to get all these `transactionId`s and then query `transactionInfo.pinpoint` with them, this would solve my problem.

**Comment by koo-taejin** [comment]
@martinstraesser 

We do not have plans to make the apis you mentioned.
Therefore, if you need it, you have to make it yourself.

`com.navercorp.pinpoint.web.service.FilteredMapServiceImpl # selectTraceIdsFromApplicationTraceIndex `
You can get the information you want through this method.
I think it will be very simple because You only need to develop a Controller that uses this method.

Thank you. :)

**Comment by martinstraesser** [comment]
Okay thank you for your responses, I will try my best to get this done :)

**Comment by dongjunwen** [comment]
TransactionId 中不存在SpanId,这个还是实现不了

**Comment by dongjunwen** [comment]
@martinstraesser 你这边已经完成了吗？代码能不能发出来参考一下？

**Comment by minwoo-jung** [comment]
@dongjunwen
 Hello, please translate your issue into English for the community.

**Comment by martinstraesser** [comment]
@dongjunwen Not sure what the first comment means, as mentioned you should translate this in english.

For the second question however, my translator says that you asked whether I implemented the controller and can provide the code. The answer is, that I postponed the development of this controller because other things have higher priorities in my project at the moment. However, what I did implement is just a simple caching mechanism which tracks the most recent valid `transactionId` for every monitored application. This is suitable for me at the moment as I send requests to Pinpoint with subsequent monitoring intervals only. So, basically the idea is if I processed the transaction `agent-1^1575622767457^1` the next id to ask for this agent is `agent-1^1575622767457^2` and so on.

If you are working on such a controller mentioned above, feel free to share your code/ideas as well.

**Comment by dinesh4747** [comment]
@martinstraesser  - How does the traceid propagate across services? I hope it should be transported via HTTP response header and If Yes do we pass any specific pinpoint Key/value pair for trace id in the header

Any insights would help a lot

**Comment by martinstraesser** [comment]
@dinesh4747 I cant answer this question because it is not relevant for my work at the moment. I'm simply requesting the traces from Pinpoint Web using the traceid. However, Pinpoint members should be able to answer this, maybe @minwoo-jung @koo-taejin
