### ISSUE TITLE
issue about passing the request parameters from the real clients to tomcat agents

### ISSUE THREAD

**Issue by davidleecn** [naver/pinpoint#6270]
Hi, 
Because our app is used as a platform for other third parties, so we provide a unique appID to others ,our app deploy in tomcat web , and I use the nginx as the proxy server to tomcat ,so in my condition ,I need to pass the third-parties' request parameters to the pinpoint's agent, especially we need the appID which is located in the request body of the different third-parties' request URI , so that we can distinguish which client requests our api .

And now I just can get the real client IP and elapsed time from nginx to tomcat according to the docs from official website ( see here https://github.com/naver/pinpoint/blob/master/doc/proxy-http-header.md ), but I don't know how to pass other request headers and request bodies to pinpoint , and by the way ,the arguments in the above docs about the proxy setup section is  ambiguous, say "t= ","D= ",what do them mean exactly ?Could I used any other args as the variable names ? 

please gimme a help about my situation .
thanks in advance !

**Comment by jaehong-kim** [comment]
@davidleecn 
Hi
The options "t =" and "D =" are based on apache. 

%t | The time the request was received in Universal Coordinated Time since the epoch (Jan. 1, 1970) measured in microseconds. The value is preceded by t=.
-- | --
%D | The time from when the request was received to the time the headers are sent on the wire. This is a measure of the duration of the request. The value is preceded by D=. The value is measured in microseconds.

No other options are supported yet.

Reference
* http://httpd.apache.org/docs/2.4/en/mod/mod_headers.html
