### ISSUE TITLE
Error in Windows 7 environment

### ISSUE THREAD

**Issue by kevinzpw** [naver/pinpoint#6341]
@minwoo-jung 
hello：
I turn on the pinpoint in the window environment
Error in Windows 7 environment：
ClassNotFoundException：com.naver.pinpoint.common.util.CodeSourceUtils

The native Java environment is normal，The package was downloaded from the official website。
Please help me thank you

**Comment by minwoo-jung** [comment]
It is very difficult to find the cause of a problem by using an exception message alone.
Please answer all the questions below.

----
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### Describe the bug
A clear and concise description of what the bug is.

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran '...' with agent attached
2. '...' method invoked
3. '...' interceptor threw '...' exception

#### Expected behavior
A clear and concise description of what you expected to happen.

#### Screenshots
If applicable, add screenshots to help explain your problem.

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by kevinzpw** [comment]
@minwoo-jung 

1.      I used the version 1.8.3 and I download  in  official  website ，I used the version java 1.6.0.3 . in Windows 7 environment 
2.     After I start the call jar package ,I got the error:  ClassNotFoundException：com.naver.pinpoint.common.util.CodeSourceUtils 
3.    ![2824a13bc4d779a724dbd526038b03e](https://user-images.githubusercontent.com/45220363/71139315-cb2dfd80-2248-11ea-8f21-8ec84d7ea511.jpg)


please help me thank you

**Comment by emeroad** [comment]
1. Upgrade old JVM.
- Your JVM is too old. 1.6.0_45 is recommended.
   - https://docs.oracle.com/javase/6/docs/api/java/lang/instrument/package-summary.html
      There seems to be a problem with the Boot-Class-Path behavior in older JVMs.
2. Upgrade Pinpoint version
- 1.8.5 is recommended

Try the above recommendations.
