### ISSUE TITLE
If the interceptor throws an exception, will it affect the application?

### ISSUE THREAD

**Issue by JangNum** [naver/pinpoint#6426]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I know that the interceptor adds and runs the before method before the monitored method. If the before method throws an exception, will it affect the execution of the application method after the before?

**Comment by minwoo-jung** [comment]
The application is affected by the exception.
So when developing interceptors, you should consider exceptions. 
n other words, development should be done so that no exception occurs.
It also implements the logic for exception handling directly in the interceptor.
ex) [ExceptionHandleAroundInterceptor0.java](https://github.com/naver/pinpoint/blob/ce0c257122a621f64d578b6258627c7d75c91333/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/interceptor/ExceptionHandleAroundInterceptor0.java)
