### ISSUE TITLE
can not show Internal execution steps 

### ISSUE THREAD

**Issue by zhouhuicong** [naver/pinpoint#6436]
why the pinpoint not show  Internal execution steps ,and how can i Solve the problem.

![1](https://user-images.githubusercontent.com/40559605/72675942-9c64aa80-3ac6-11ea-95fc-5818e4d7f1d6.png)

**Comment by koo-taejin** [comment]
hi @zhouhuicong 

This is caused by using UDP for trace data to transfer.
If use UDP transport, packets are not retransmitted, so packets may be dropped.

If the trace data is large, the data is fragmented and sent to the collector according to the UDP packet size.
If part of the fragmented data is lost, recombination is not possible, so the calltack is being rendered as lost.

I recommend you to divide into several in one batch trace by setting (using entryPoint setting),
or disable plugins that you don't think are unnecessary,
then the probability of the above problem is greatly reduced.

This can happen if the cpu or network is busy in the server, but there is no problem with the application.

Beginning with 2.0.0, the default setting is to send span for TCP. It is expected that this phenomenon will be reduced.
I recommend using 2.0.0-RC2 if possible.

If the same happens in 2.0.0-RC2, please post the agent log collector log together.

thanks. :)
