### ISSUE TITLE
Alert on agent disconnected

### ISSUE THREAD

**Issue by davide-parini** [naver/pinpoint#6515]
Is it possible to configure an alarm to warn me whenever an agent is disconnected? I would like to be notified whenever a monitored application crashes and stops reporting to Pinpoint.

**Comment by koo-taejin** [comment]
hi @davide-parini 

Pinpoint does not support feature that you mentioned.

This issue requires some judgments.
* Reconnection due to network issues 
* Which of four connections to include

I would think about this feature.

However, even if I think positively, it is not a feature that can be provided in a short time.
Perhaps I think that developing it yourself will be faster.

thanks :)

**Comment by davide-parini** [comment]
Ok thank you @koo-taejin!

**Comment by doyoung-kim** [comment]
잘 봤습니다.
