### ISSUE TITLE
TransId is passed across the thread pool in asynchronous execution

### ISSUE THREAD

**Issue by chkch** [naver/pinpoint#6556]
I hope that I can provide a solution for the transfer of TransId across threads and thread pools in asynchronous execution. Recently I saw an open source class library of Alibaba. I think it may be helpful for this. I hope that I can support TransId asynchronous across thread pools as soon as possible transfer.

https://github.com/alibaba/transmittable-thread-local

**Comment by chkch** [comment]
Hi, @koo-taejin , if you have time to look at the TransmittableThreadLocal mentioned in the link above, can pinpoint use the principle of TTL to enhance the asynchronous call using the thread pool

**Comment by koo-taejin** [comment]
hi @chkch 

Thank you for sharing this project with me.
However, it is difficult to understand because most of documents are written in Chinese.

Fortunately, we have been handling properly asynchronous call without any difficulties. (Although It has more work than the synchronous call.)

If I meet big problem to handle asynchronous call, then I will consider it deeply.

thanks :)

**Comment by superbool** [comment]
@koo-taejin Here is English documents  about https://github.com/alibaba/transmittable-thread-local
https://github.com/alibaba/transmittable-thread-local/blob/master/README-EN.md
