### ISSUE TITLE
Compatible with low version Java High Level REST Client

### ISSUE THREAD

**Issue by chkch** [naver/pinpoint#6650]
Hi, @koo-taejin @RoySRose , we use the elasticsearch cluster is 6.8.2, but see that the plug-in supports 7.2.0, because ES is not backward compatible, it will not be able to identify ES correctly, may I be compatible with the lower version of Java High Level REST Client

**Comment by chkch** [comment]
I see in the code that there is annotated code that supports different versions of the cluster
![1](https://user-images.githubusercontent.com/31233516/77753330-3a936480-7064-11ea-806c-6378fe99e711.png)

![2](https://user-images.githubusercontent.com/31233516/77753318-36674700-7064-11ea-9d6b-a3f0bba8317d.png)

**Comment by RoySRose** [comment]
Hello, @chkch 

It's been some time since I developed this plugin, so I'm not sure if I can recall it correctly.

So far, I remember the intention was to support from v6.0.0. 
But since there wasn't a hard user in ES around us. It may be hard to check ALL possible cases.

That commented codes are to get version from the cluster.
What's your situation? do you need to retrieve the version? or is there any other kind of a problem?

**Comment by chkch** [comment]
Hi, @RoySRose 
The cluster version I am using is V6.8.2, but it is not recognized in the application topology diagram and call relationship. Please give some valuable suggestions, thank you

**Comment by RoySRose** [comment]
@chkch 
For exact reasons, I need to look at Elasticsearch library and your connection/execution part of the code. Since I'm caught up on other things at the moment.

You can also check `com.navercorp.pinpoint.plugin.elasticsearch.ElasticsearchPlugin.java` to see if the plugin is correctly instrumenting the v6.8.2.

With the comment in the code. `addElasticsearchExecutorInterceptors` method looks like it takes care of Connecting and Executing for v6.8.2

Following the code, inside `ExecutorTransformCallback` class. The constructor is being instrumented. You can check if this is also correct for v6.8.2.

The plugin code is very intuitive and simple when you get to know it.
Hope you can find the missing part and make some contributions :)

**Comment by chkch** [comment]
@RoySRose 
I found that I was wrong, ES was recognized in the link information, but it was not shown in the topology diagram,I will try to update the collector version to see if this resolves the issue.

**Comment by RoySRose** [comment]
:) great, love to hear the feedback

**Comment by chkch** [comment]
@RoySRose 
I found that there is no elasticsearch.png image under the directories img/icons and img/servermap.
Do you know why?
