### ISSUE TITLE
pinpoint-activemq-plugin-it cause build failure.

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#6803]
#### What version of pinpoint are you using?
master/2.0.2

#### Describe the bug
pinpoint-activemq-plugin-it got build failure.
The related build output is as following:

> ...
> [INFO]
> [INFO] ---------< com.navercorp.pinpoint:pinpoint-activemq-plugin-it >---------
> [INFO] Building pinpoint-activemq-plugin-it 2.0.2                     [111/156]
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ pinpoint-activemq-plugin-it ---
> [INFO] Deleting /path/pinpoint/plugins-it/activemq-it/target
> [INFO]
> [INFO] >>> maven-source-plugin:3.2.1:jar (default-cli) > generate-sources @ pinpoint-activemq-plugin-it >>>
> [INFO]
> [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-pinpoint-build-requirements) @ pinpoint-activemq-plugin-it ---
> [INFO]
> [INFO] <<< maven-source-plugin:3.2.1:jar (default-cli) < generate-sources @ pinpoint-activemq-plugin-it <<<
> [INFO]
> [INFO]
> [INFO] --- maven-source-plugin:3.2.1:jar (default-cli) @ pinpoint-activemq-plugin-it ---
> [INFO] No sources in project. Archive not created.
> [INFO]
> [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-pinpoint-build-requirements) @ pinpoint-activemq-plugin-it ---
> [INFO]
> [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ pinpoint-activemq-plugin-it ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /path/pinpoint/plugins-it/activemq-it/src/main/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ pinpoint-activemq-plugin-it ---
> [INFO] No sources to compile
> [INFO]
> [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ pinpoint-activemq-plugin-it ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 2 resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ pinpoint-activemq-plugin-it ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 14 source files to /path/pinpoint/plugins-it/activemq-it/target/test-classes
> [WARNING] /path/pinpoint/plugins-it/activemq-it/src/test/java/com/navercorp/pinpoint/plugin/activemq/client/ActiveMQClientITBase.java:[119,110] non-varargs call of varargs method with inexact argument type for last parameter;
>   cast to ExpectedAnnotation for a varargs call
>   cast to ExpectedAnnotation[] for a non-varargs call and to suppress this warning
> [WARNING] /path/pinpoint/plugins-it/activemq-it/src/test/java/com/navercorp/pinpoint/plugin/activemq/client/ActiveMQClientITBase.java:[297,101] non-varargs call of varargs method with inexact argument type for last parameter;
>   cast to ExpectedAnnotation for a varargs call
>   cast to ExpectedAnnotation[] for a non-varargs call and to suppress this warning
> [INFO]
> [INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ pinpoint-activemq-plugin-it ---
> [INFO] Tests are skipped.
> [INFO]
> [INFO] --- animal-sniffer-maven-plugin:1.18:check (ensure-java-1.7-class-library) @ pinpoint-activemq-plugin-it ---
> [INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
> [INFO]
> [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ pinpoint-activemq-plugin-it ---
> [WARNING] JAR will be empty - no content was marked for inclusion!
> [INFO] Building jar: /path/pinpoint/plugins-it/activemq-it/target/pinpoint-activemq-plugin-it-2.0.2.jar
> [INFO]
> [INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ pinpoint-activemq-plugin-it ---
> [INFO] Tests are skipped.
> [INFO]
> [INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ pinpoint-activemq-plugin-it ---
> [INFO] Tests are skipped.
> [INFO]
> [INFO] --- maven-install-plugin:2.4:install (default-install) @ pinpoint-activemq-plugin-it ---
> [INFO] Installing /path/pinpoint/plugins-it/activemq-it/target/pinpoint-activemq-plugin-it-2.0.2.jar to /path/.m2/repository/com/navercorp/pinpoint/pinpoint-activemq-plugin-it/2.0.2/pinpoint-activemq-plugin-it-2.0.2.jar
> [INFO] Installing /path/pinpoint/plugins-it/activemq-it/pom.xml to /path/.m2/repository/com/navercorp/pinpoint/pinpoint-activemq-plugin-it/2.0.2/pinpoint-activemq-plugin-it-2.0.2.pom
> [INFO]
> [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-pinpoint-build-requirements) @ pinpoint-activemq-plugin-it ---
> [INFO]
> [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ pinpoint-activemq-plugin-it ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /path/pinpoint/plugins-it/activemq-it/src/main/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ pinpoint-activemq-plugin-it ---
> [INFO] No sources to compile
> [INFO]
> [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ pinpoint-activemq-plugin-it ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 2 resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ pinpoint-activemq-plugin-it ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO]
> [INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ pinpoint-activemq-plugin-it ---
> [INFO] Tests are skipped.
> [INFO]
> [INFO] --- animal-sniffer-maven-plugin:1.18:check (ensure-java-1.7-class-library) @ pinpoint-activemq-plugin-it ---
> [INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.0
> [INFO]
> [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ pinpoint-activemq-plugin-it ---
> [WARNING] JAR will be empty - no content was marked for inclusion!
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] pinpoint 2.0.2 ..................................... SUCCESS [  2.929 s]
> ....
> [INFO] pinpoint-plugin-it-utils ........................... SUCCESS [  1.528 s]
> [INFO] pinpoint-plugin-it-jdbc-test ....................... SUCCESS [  3.629 s]
> [INFO] pinpoint-activemq-plugin-it ........................ FAILURE [  1.886 s]
> [INFO] pinpoint-cassandra-plugin-it ....................... SKIPPED
> [INFO] pinpoint-cxf-plugin-it ............................. SKIPPED
> [INFO] pinpoint-druid-plugin-it ........................... SKIPPED
> [INFO] pinpoint-dubbo-plugin-it ........................... SKIPPED
> ...
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.0:jar (default-jar) on project pinpoint-activemq-plugin-it: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
> 

#### What did you do to trigger the bug?
./mvnw -DskipTests=true clean source:jar install deploy -Prelease

#### Expected behavior
Build successfully.

#### Quick Workaround
Comment out plugins-it module.

**Comment by emeroad** [comment]
@yjqg6666 
Hi. This problem is not reproduced.

/mvnw -DskipTests=true clean source:jar install -Prelease

I tested with the above command, but there was no problem



>[INFO] pinpoint-activemq-plugin-it ........................ SUCCESS [  1.102 s]
[INFO] pinpoint-cassandra-plugin-it ....................... SUCCESS [  1.014 s]
[INFO] pinpoint-cxf-plugin-it ............................. SUCCESS [  0.773 s]
[INFO] pinpoint-druid-plugin-it ........................... SUCCESS [  1.096 s]
[INFO] pinpoint-dubbo-plugin-it ........................... SUCCESS [  0.825 s]
[INFO] pinpoint-elasticsearch-bboss-plugin-it ............. SUCCESS [  1.182 s]
[INFO] pinpoint-elasticsearch-plugin-it ................... SUCCESS [  1.026 s]
[INFO] pinpoint-fastjson-plugin-it ........................ SUCCESS [  0.672 s]
[INFO] pinpoint-grpc-plugin-it ............................ SUCCESS [  1.558 s]
[INFO] pinpoint-google-httpclient-plugin-it ............... SUCCESS [  0.684 s]
[INFO] pinpoint-google-httpclient-plugin-jdk7-it .......... SUCCESS [  0.758 s]
[INFO] pinpoint-gson-plugin-it ............................ SUCCESS [  0.655 s]
[INFO] pinpoint-hbase-plugin-it ........................... SUCCESS [  0.847 s]
[INFO] pinpoint-httpclient3-plugin-it ..................... SUCCESS [  0.664 s]
[INFO] pinpoint-httpclient4-plugin-it ..................... SUCCESS [  0.775 s]
[INFO] pinpoint-hikaricp-plugin-it ........................ SUCCESS [  0.673 s]
[INFO] pinpoint-hikaricp-plugin-jdk7-it ................... SUCCESS [  0.734 s]
[INFO] pinpoint-hystrix-plugin-it ......................... SUCCESS [  0.879 s]
[INFO] pinpoint-ibatis-plugin-it .......................... SUCCESS [  0.812 s]
[INFO] pinpoint-informix-jdbc-driver-plugin-it ............ SUCCESS [  0.937 s]
[INFO] pinpoint-jackson-plugin-it ......................... SUCCESS [  0.759 s]
[INFO] pinpoint-jackson-plugin-jdk7-it .................... SUCCESS [  0.880 s]
[INFO] pinpoint-jdk-http-plugin-it ........................ SUCCESS [  0.685 s]
[INFO] pinpoint-json-lib-plugin-it ........................ SUCCESS [  0.690 s]
[INFO] pinpoint-log4j2-plugin-it .......................... SUCCESS [  0.710 s]
[INFO] pinpoint-log4j2-plugin-jdk8-it ..................... SUCCESS [  0.751 s]
[INFO] pinpoint-log4j-plugin-it ........................... SUCCESS [  0.625 s]
[INFO] pinpoint-logback-plugin-it ......................... SUCCESS [  0.618 s]
[INFO] pinpoint-mariadb-jdbc-driver-plugin-it ............. SUCCESS [  0.892 s]
[INFO] pinpoint-mongodb-plugin-it ......................... SUCCESS [  0.867 s]
[INFO] pinpoint-mssql-jdbc-driver-plugin-it ............... SUCCESS [  0.930 s]
[INFO] pinpoint-mybatis-plugin-it ......................... SUCCESS [  0.696 s]
[INFO] pinpoint-netty-plugin-it ........................... SUCCESS [  0.755 s]
[INFO] pinpoint-ning-aysncclient-plugin-it ................ SUCCESS [  0.697 s]
[INFO] pinpoint-okhttp-plugin-it .......................... SUCCESS [  0.827 s]
[INFO] pinpoint-thrift-plugin-it .......................... SUCCESS [  1.048 s]
[INFO] pinpoint-rabbitmq-plugin-it ........................ SUCCESS [  1.324 s]
[INFO] pinpoint-rxjava-plugin-it .......................... SUCCESS [  0.885 s]
[INFO] pinpoint-spring-plugin-it .......................... SUCCESS [  0.789 s]
[INFO] pinpoint-thread-plugin-it .......................... SUCCESS [  0.699 s]
[INFO] pinpoint-process-plugin-it ......................... SUCCESS [  0.654 s]
[INFO] pinpoint-web ....................................... SUCCESS [01:43 min]
[INFO] pinpoint-hbase-distribution ........................ SUCCESS [  0.505 s]
[INFO] pinpoint-hbase-schema-definition ................... SUCCESS [  2.501 s]
[INFO] pinpoint-hbase-schema .............................. SUCCESS [  3.594 s]
[INFO] pinpoint-hbase-schema-manager ...................... SUCCESS [  4.050 s]
[INFO] pinpoint-flink 2.0.3-SNAPSHOT ...................... SUCCESS [ 11.397 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:37 min
[INFO] Finished at: 2020-05-20T15:40:32+09:00
[INFO] ------------------------------------------------------------------------

**Comment by yjqg6666** [comment]
java version:
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

**Comment by emeroad** [comment]
https://naver.github.io/pinpoint/installation.html#quick-overview-of-installation
Have you installed java 6,7,8,9?
Clean build is not guaranteed when only java 8 is installed.

**Comment by yjqg6666** [comment]
All are installed and configured properly, after commenting out plugins-it the agent/collector/web can be built successfully.

**Comment by emeroad** [comment]
I installed jdk8u222, but the problem was not reproduced.

JDK version
> JAVA_6_HOME=C:\Develop\Java\jdk1.6.0_45
JAVA_7_HOME=C:\Develop\Java\jdk1.7.0_80
JAVA_8_HOME=C:\Develop\openjdk\jdk8u222-b10  <-- update 8u222
JAVA_9_HOME=C:\Develop\openjdk\jdk-9+181
JAVA_HOME=C:\Develop\openjdk\jdk8u222-b10

Can I know the installed JDK version?

**Comment by yjqg6666** [comment]
Run the command from MacOs and Linux from which we build PinPoint for testing & release.

> for i in $(env|grep 'JAVA' |grep 'HOME');do echo -e "\n";echo $i;p=$(echo $i|cut -d'=' -f2);$p/bin/java -version;done

## On Macos 1.0.15.4 
JAVA_11_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

JAVA_6_HOME=/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

JAVA_7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

JAVA_8_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

JAVA_9_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-9.jdk/Contents/Home
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)




# On Linux 3.10.0-957.27.2.el7.x86_64 （Use the latest master, can build successfully. I am checking v2.0.2, and will update result soon.)

JAVA_6_HOME=/root/jdk/jdk1.6.0_45
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

JAVA_9_HOME=/root/jdk/jdk-9.0.4
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

JAVA_HOME=/root/jdk/jdk1.8.0_221
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

JAVA_7_HOME=/root/jdk/jdk1.7.0_80
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

JAVA_8_HOME=/root/jdk/jdk1.8.0_221
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by yjqg6666** [comment]
https://github.com/naver/pinpoint/blob/master/plugins-it/activemq-it/pom.xml#L32-L33

>     <properties>
>         <jdk.version>1.7</jdk.version>
>         <jdk.home>${env.JAVA_7_HOME}</jdk.home>
>     </properties>

It may be JDK7-related. I will look it up further and update it soon.

**Comment by yjqg6666** [comment]
I cleaned my local repository(~/.m2/repository/com/navercorp/pinpoint/pinpoint）and build from scratch. 
Now it's working and sorry for wasting your time and thanks a lot for your help. 
We build our customized branch using the same version 2.0.2. After check&building the original tag v2.0.2 successfully, we rebuild our branch it works. After deleting the local repository, rebuild again and it also works.

 I will consider using version 2.0.2-xxx for ourselves, would it cause any malfunction?

**Comment by emeroad** [comment]
Good idea, maybe there's no problem
