### ISSUE TITLE
Memory profiler feature

### ISSUE THREAD

**Issue by HanishRamc** [naver/pinpoint#6856]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

I'm wondering if there is memory profiler or memory snapshot captured at JVM level would be great. 

Kindly share the details if there is any way to detect out of memory situation

Regards
Ramc

**Comment by koo-taejin** [comment]
hi @HanishRamc 

I think it seems like heapdump. 
Pinpoint does not support to make heapdump. 
It is because heapdump extraction takes a very long time, and application will be stop during making heapdump.

For this reason, I recommend you extracting the heap dump in other environments.  

thanks :)

**Comment by HanishRamc** [comment]
Thanks for your comments @koo-taejin .

I expect to have heap memory summary only histogram and compare Objects usage trend  as on optional feature.
Thanks
Ramc
