### ISSUE TITLE
Trace Id search

### ISSUE THREAD

**Issue by Chao-Zeng** [naver/pinpoint#7120]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Are there any plan to support trace id search in pinpoint?

**Comment by yjqg6666** [comment]
Already support trace id search since version 2.0.3. You may check [the demo ](http://125.209.240.10:10123/main/ApiGateway@SPRING_BOOT/5m/2020-08-17-18-05-29?inbound=1&outbound=4&wasOnly=false&bidirectional=false)
![image](https://user-images.githubusercontent.com/1879641/90384638-77fc9b00-e0b4-11ea-8f56-4a1a6776c23f.png)

Paste a trace id there and press "Enter".

**Comment by Chao-Zeng** [comment]
thanks for your reply

**Comment by yjqg6666** [comment]
Only the servlet requests would be logged, you can check the web first. And your log transaction config is set to true for your logger, log4j or/and log back.
